### ISSUE TITLE
Pricing/Licensing versus Analytical Workspaces and LCS pbix files.

### ISSUE THREAD

**Issue by Hettic** [MicrosoftDocs/dynamics-365-unified-operations-public#1]
There is a lot of confusion about pricing/licensing according to analytical workspaces and pushing LCS files to PowerBI.com.

People are mixing those things up. Maybe you could somehow integrate the picture in the docs.
![aw versus powerbi com](https://user-images.githubusercontent.com/16560913/32104499-fcf0dcee-bb24-11e7-941e-475531dc87b2.jpg)

**Comment by MargoC** [comment]
Instead of using GitHub issues, please consider these options if you need help or have feedback:

-	Feedback or questions about technical articles are best handled through the Livefyre thread at the bottom of each article. This makes it clear to us which article you are talking about.

-	Suggested changes to technical articles are best handled as proposals for change through pull requests. Each pull request is reviewed by the article author or a related subject matter expert for the article.

-	If you need support using Microsoft Dynamics 365 for Finance and Operations, your best bets are the Dynamics 365 community forums (https://community.dynamics.com/) and our support channels. For more information about support, see https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support.

-	Product and feature feedback is best handled through the Dynamics 365 Ideas Portal: https://ideas.dynamics.com/ideas/

**Comment by jawn** [comment]
@MargoC 
To avoid more issues like this, how about adding your answer to the [README](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/blob/live/README.md)?

**Comment by MargoC** [comment]
Good idea. We're also setting up an auto-reply for issues.
