### ISSUE TITLE
Detail countryspecific resources for VAT statements

### ISSUE THREAD

**Issue by bjool** [MicrosoftDocs/dynamics-365-unified-operations-public#1035]
There are documentation missing for multiple countries in this list; Sweden and United Kingdom for example. Both have special VAT reports developed with a required and recommended setup which should be included here as implementation guidelines. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b93833-d8a1-acca-deab-b09919a9cd05
* Version Independent ID: 309dd00f-9a84-f3ef-4445-836940030f93
* Content: [VAT reporting for Europe - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/localizations/emea-vat-reporting#feedback)
* Content Source: [articles/financials/localizations/emea-vat-reporting.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/localizations/emea-vat-reporting.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @ShylaThompson
* Microsoft Alias: **v-elgolu**

**Comment by ShylaThompson** [comment]
@LizaGolub  Please review this issue and update the topic if necessary.

**Comment by LizaGolub** [comment]
Hello,
Thank you for your comment. The article mentioned is dedicated to the process of VAT statement generation when data collection is based on Reporting codes and Electronic reporting format. United Kingdom VAT statement cannot be included into this list as this report doesn't use Reporting codes setup and such association could introduce a confusion in understanding of how to setup system for it. For Sweden and Finland there is no specific VAT statement electronic reporting format supported for now. These countries are in the list at the top of the article because Reporting codes are used by these countries in setup of sales tax but there is no specific articles because of absence of specific electronic reporting format.
