### ISSUE TITLE
Screenshots would be helpful (and more)

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#1163]
1) This article would profit from screenshots. User could compare his screen to what the configuration should look like.
2) It is strange that inputs are duplicated as a bullet point.
3) The instruction does not cover if the objects are created as a parent-child hierarchy or all as root objects. Starting from the second "click add", the system asks me if I want to create a root object or a CHILD to the previously selected object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d76f0af3-e987-1800-eed4-b813db42fb5e
* Version Independent ID: c4af31bf-8cb5-4619-d9ff-650182eaf39b
* Content: [ER Design domain specific data model - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11#feedback)
* Content Source: [articles/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/tasks/er-design-domain-specific-data-model-2016-11.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@SST1982, thanks for providing this feedback!

@NickSelin, please review and update the topic accordingly.

**Comment by ShylaThompson** [comment]
@SST1982  Thanks for logging this issue. Topics like this one were automatically generated from a task guide. If your help system parameters are set up so you have access to the most recent Microsoft APQC Business Process Modeler Library, you should have access to the task guide that that this topic was created from. Task guides walk you through procedures in the user interface. See this topic about [task guides](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/help-overview#task-guides) for more information. If you play the task guide, this should clear up the immediate questions you have.

We've started updating some of the task guide topics for readability, so this issue is related to an existing project that is under way. Because this is issue is related to planned work, I'm closing this issue.
