### ISSUE TITLE
Update instructions for OneVersion environments and local development vhd environments

### ISSUE THREAD

**Issue by FH-Inway** [MicrosoftDocs/dynamics-365-unified-operations-public#1183]
Some parts of the article do not seem the current update process for OneVersion platform updates and/or local development vhd environments. For example, in the current platform update 25 installer package, there is no PlatformUpdatePackages.Config file as mentioned in section "Apply a platform update to environments that are not connected to LCS".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d220b-d85d-eabd-abfb-8fadb3b8bf47
* Version Independent ID: c25f2d4d-dfef-7736-311f-8c1f25ddc696
* Content: [Apply the latest platform update to environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/upgrade-latest-platform-update)
* Content Source: [articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/upgrade-latest-platform-update.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @tariqbell
* Microsoft Alias: **tabell**

**Comment by sericks007** [comment]
@FH-Inway, thanks for posting this!

@manalidongre, please review and update the topic as needed.

**Comment by sericks007** [comment]
Bug 316728 has been logged to track this issue.

**Comment by noakesey** [comment]
In addressing this, please could you consider updating step 4 in "Install the deployable package" so that it reads:

"Follow the instructions for installing a deployable package _and ensure that the DefaultTopologyData.xml file is updated for your environment._ See ... [etc]"

It is possible for the reader to skip over the updates to DefaultTopologyData.xml in the next page as they are enclosed with a section that refers to LCS environments again (this section is about non LCS environments).

There a lot of issues on Yammer that seem to be caused by this (I came a cropper the first time as well and didn't think it necessary to update DefaultTopologyData.xml...)

**Comment by FH-Inway** [comment]
@noakesey I created a similar [issue 1137](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1137) for another article, maybe bug 313995 created there could also be used for your feedback.
