### ISSUE TITLE
Privilege AOT name incorrect

### ISSUE THREAD

**Issue by FINOPSAOSCEWA** [MicrosoftDocs/dynamics-365-unified-operations-public#1285]
There is no privilege object named as "FinancialReportsSecurityMaintain".
It might be "FinancialReportsSecuritySystemMaintain" which you want to write down.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b457809-75fe-b874-a8e3-04024b2000b2
* Version Independent ID: bfebff81-9d43-3a97-5f3a-90849a28db87
* Content: [Financial reporting - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/financial-reporting-getting-started#feedback)
* Content Source: [articles/financials/general-ledger/financial-reporting-getting-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/financial-reporting-getting-started.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by josaw1** [comment]
Thank you for your feedback. @aprilolson, can you please take a look?

**Comment by aprilolson** [comment]
Can you please assign to ryan sandness?

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by josaw1** [comment]
@ryansandness

**Comment by sericks007** [comment]
@FINOPSAOSCEWA, thanks for making us aware of this issue.  The fix has been made and will be published later this week.
