### ISSUE TITLE
Company limits

### ISSUE THREAD

**Issue by DFKA** [MicrosoftDocs/dynamics-365-unified-operations-public#1373]
Might be useful if the actual company limitation is mentioned (max 100).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dccb9a2-7862-923a-aeaf-90911d9d8b3f
* Version Independent ID: 4e2ad7f3-2c22-54c0-56cb-802af92adaaf
* Content: [Cross-company data sharing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/cross-company-data-sharing#feedback)
* Content Source: [articles/dev-itpro/sysadmin/cross-company-data-sharing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/cross-company-data-sharing.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by josaw1** [comment]
Thank you for your feedback. 
@aprilolson, can you please review?

**Comment by aprilolson** [comment]
Hi Jo,
This article owner should be Sunil Garg, so please assign to him. Thanks!

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by josaw1** [comment]
@Sunil-Garg, can you please review this feedback? Thanks.

**Comment by RobinARH** [comment]
Bug 335732 created to track this issue.
