### ISSUE TITLE
Build requires use of the installed package's descriptor

### ISSUE THREAD

**Issue by MarkerMarked** [MicrosoftDocs/dynamics-365-unified-operations-public#1451]
When following the guide, on adding the package's files to source code I left out the 'XppMetadata' and 'Descriptor' as instructed. However on running a build in VSTS, I hit an error "Error generating build projects". This was due to my new model being referenced from another, and the new model was not found. 
On checking in the descriptor file, I restarted the build which completed successfully. It seems this file is required.

The last two posts on this MS forums link seems to also agree:
https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/275117/vsts-artifact-publication-failing

Thank you for the guide, I hope this is corrected if the descriptor file is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0a6db2-4e72-d3aa-c76e-60f77889e384
* Version Independent ID: 5bf086ca-5ca6-c0be-e2a7-6ad737bf4217
* Content: [Manage third-party models and runtime packages by using source control - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-tools/manage-runtime-packages#feedback)
* Content Source: [articles/dev-itpro/dev-tools/manage-runtime-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-tools/manage-runtime-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
Adding the descriptor file will result in the build compiling the whole package. This is a different intention than adding binaries from a third party. The documentation is entirely correct and has been followed by many customers.
Please review your intention: are you adding third-party source code? Than follow the "models from third parties" section. Do you have binaries from a third party which you want to re-package and/or use during build? Use the "deployable packages from third parties" section.

If you have binaries and the guide didn't work, you either missed to include some files from "Bin" (as the article states - make sure Visual Studio didn't exclude ANY files from checking!) are you actually don't have the binaries (since you have a descriptor it implies you have the source code).
