### ISSUE TITLE
“BusinessEventsBundleBatchProcessor “ is not existing from the batch job UI

### ISSUE THREAD

**Issue by johnhenryboco** [MicrosoftDocs/dynamics-365-unified-operations-public#1456]
Hi Experts.

In Platform Upgrade 27, I see that you guys revised the rules on how the business event is being triggered. Currently i created a customization in which after running the business events batch job (this batch job gets data from the BUSINESSEVENTSCOMMITLOG table), an MS Flow Business event will be triggered and sends an email. However, I'm trying to digest on what do you mean by this statement: "Dedicated threads are allocated to process business events by the system, which ensures faster processing of business events." -&gt; So do you mean, automatically? Since batch jobs in PU 27 are now ineffective? So the current situation is not working for us as of the moment, thus prompted to do the workaround from your article (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/home-page#business-events-processing) However, BusinessEventsBundleBatchProcessor class does not even exist from the batch UI. I would greatly appreciate if you guys can help me trigger the business events. That would be so much helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655c157f-5478-4c71-7cd4-1b04383264ee
* Version Independent ID: 6555a353-87cd-c919-0c3e-dcfc4ede9909
* Content: [Business events - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/home-page#feedback)
* Content Source: [articles/dev-itpro/business-events/home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/business-events/home-page.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@johnhenryboco, thanks for the feedback. 
@Sunil-Garg, please review and consider making updates to the topic. 
Bug 342562 has been logged to track this issue.

**Comment by jonathansulte** [comment]
i am on PU28 and i cannot seem to get the event to trigger either. i am setting up Flow integration in our Tier-2 Sandbox environment. am i missing a step?

1. Enable Business Event
2. Create an MS Flow. 
3. Trigger the event. (i have tried When Invoice is Created on Sales Order and When an alert rule is triggered)

is there any Batch Job that i need to have running in the background?

**Comment by Sunil-Garg** [comment]
Pls check the troubleshooting guide. The last issue described is most likely the reason. Let us know if that does not help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonathansulte** [comment]
thanks @Sunil-Garg . are you able to post the link to the specific one you are refering to? thanks in advance

**Comment by Sunil-Garg** [comment]
Here is the link https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/business-events/troubleshooting

Specifically, pls use the following fix to make this work. If this does not help, pls email me at sunilg@microsoft.com and we can take a look.

One of the reasons why this issue can occur is if certain parameters are not set as expected in the BusinessEventsParameters table. This is due to an update in which some of the business events parameters not being set correctly.

In a non-production environment, you must update the BusinessEventsParameters table so that Enabled =1; ProcessorThreads = 1; EndPointRetryCount = 3; BundleSize = 50; EndPointsPerEvent = 10. After this update, restart the batch service and run IISReset to pick up the latest values.

For production environments, log a support request with Microsoft to get these updated.

**Comment by TKispoev** [comment]
@Sunil-Garg
The sentence "This behavior is controlled using a parameter in the business events parameter table, which is turned off by default to indicate that manual batch job will not be effective by default" can be updated clarifying that the name of the parameter is "BATCHENABLED" and it must be set to 0 for the dedicated job to work. Cross reference to the troubleshooting page can be added as well. This seems to be a common issue when Business events are not getting triggered at all because the BATCHENABLED is set to 1

**Comment by Sunil-Garg** [comment]
Thanks. The wiki has been updated per your suggestion.
