### ISSUE TITLE
Hourly paid workers setup

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/dynamics-365-unified-operations-public#1481]
This page says "Generate earnings from schedule is typically used for hourly workers".
But Schedule it not actual hours. How does this work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3216e38-e51c-8994-7926-927ac70e0479
* Version Independent ID: 3004dfcc-d399-9f73-7ca4-756e48789dd4
* Content: [Set up payroll for workers - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/hr/localizations/noam-usa-worker-position-payroll-tasks#adding-payroll-periods-to-positions)
* Content Source: [articles/fin-and-ops/hr/localizations/noam-usa-worker-position-payroll-tasks.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/hr/localizations/noam-usa-worker-position-payroll-tasks.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @andreabichsel
* Microsoft Alias: **ryansand**

**Comment by tonyafehr** [comment]
@turbozapekanka. thank you for the feedback. 

@ryansandness or @andreabichsel, please consider making updates to this topic based on this feedback. 

Bug 342551 has been logged to track this issue.

**Comment by ryansandness** [comment]
You can use the "transfer to pay" under time and attendance to send hours to payroll to calculate. Otherwise you'd need to look at some process to populate the earnings lines, whether through an entity or some other process. Transfer to pay example is here, but it has moved since 2012. https://dyntips.com/2015/03/21/time-and-attendance-part-2131-payroll-transfer-and-export/
