### ISSUE TITLE
Extending ERExpressionStringBase is not possible since PU26 or PU27

### ISSUE THREAD

**Issue by Apsia-asarazin** [MicrosoftDocs/dynamics-365-unified-operations-public#1504]
I'm trying to extend the class ERExpressionStringBase but now, visual studio doesn't allow it since the class has become internal and the methods are not hookable. Thus I get the following error message when compiling : Class 'ERExpressionStringBase' is internal and is not accessible from the current module '[Our Module]'. 

Could you please share how to extend the ER functions after the new updates ? Nothing is mentioned on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb9b46a-66ea-0e0c-c7e1-381da4af0a1f
* Version Independent ID: 75c59226-4213-3b3f-a8c5-7c77a36aab6a
* Content: [Extend the list of Electronic reporting (ER) functions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension#feedback)
* Content Source: [articles/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/general-electronic-reporting-formulas-list-extension.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by sericks007** [comment]
@Apsia-asarazin, thanks for posting this.

@NickSelin, please review and update the content as needed.

**Comment by NickSelin** [comment]
As described in the https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/er-apis-app73 page, starting from the 7.3 version of Dynamics 365 for Finance and Operations certain classes were marked as internal. Therefore, for the 7.3 version or higher you can’t extend the list of available ER functions any longer.

Please, consider the following options instead of introduction of custom ER functions to transform texts:
1.	Use the built-in REPLACE function defining necessary regular expressions in arguments to support complex text transformations;
2.	Implement necessary text transformation logic in methods of a new public class. Then, refer to this class from a new ER datasource of the Class type and call those methods with parameters from ER format or mapping;
3.	Register a new request for a new ER extensibility point to obtain a new built-in function.
