### ISSUE TITLE
Key Section is no longer current

### ISSUE THREAD

**Issue by orichardt** [MicrosoftDocs/dynamics-365-unified-operations-public#1541]
The current Azure AAD application iis not like the listed screenshots. It does not contain anything about keys and the path is not current - is this substituted by keyvault or other? Please advise where I can find the Application Key when registering the service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d397d-4186-c7de-431d-3260d3f0484a
* Version Independent ID: bdd7545b-5970-93e0-5cbb-a59da4ace01b
* Content: [Configure Power BI integration for workspaces - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/configure-power-bi-integration#feedback)
* Content Source: [articles/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by roschlom** [comment]
Thank you for your comment. @milindav would you please review this?

**Comment by tonyafehr** [comment]
Bug # 348403 has been logged to track this issue.

**Comment by orichardt** [comment]
any news on this?

**Comment by tonyafehr** [comment]
Instead of waiting on an update to the documentation, I suggest that you contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by orichardt** [comment]
Thank you for the feedback
