### ISSUE TITLE
Settings to automatically adjust ledger period

### ISSUE THREAD

**Issue by MichaelSlipp** [MicrosoftDocs/dynamics-365-unified-operations-public#1580]
Some modules - such as Project Management and Accounting, Expense Management - have settings to automatically change the date on transactions to an open posting period.  It is important to review these settings, as some companies may prefer to see the errors and re-open the period (eg adjusting entries for a specific period), versus having the system move the date (eg expense claims approved over period-end).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ac45e9-47b1-88d2-adf4-a0f573c561af
* Version Independent ID: 6200c670-2c0a-9874-497b-1cecfc5d81b7
* Content: [Close the general ledger at period end - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/general-ledger/close-general-ledger-at-period-end)
* Content Source: [articles/financials/general-ledger/close-general-ledger-at-period-end.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/general-ledger/close-general-ledger-at-period-end.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
@MichaelSlipp , thanks for the feedback. 
@aprilolson, consider updating this topic based on this information. Thanks!

**Comment by tonyafehr** [comment]
Bug 351745 has been logged to track this issue.

**Comment by aprilolson** [comment]
+ @Kristi Weekley (kweekley@microsoft.com)<mailto:kweekley@microsoft.com> – Kristi there is a comment if you want to update the doc.

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.
