### ISSUE TITLE
Dynamics 365 Translation Service - Complete with error on some languagues

### ISSUE THREAD

**Issue by RHaest** [MicrosoftDocs/dynamics-365-unified-operations-public#1599]
When creating a translation request based on a .xlf file, sometimes the translation service reports this as "Completed with errors" and shows no further information. When viewing the output, it shows: File could not be translated. Open a new request. This request completed with the error(s).

Strange thing is that this happens only for certain languages. So for example, I have one basefile which I want to translate to German, Dutch, French, Italian and Spanish. German, Dutch, French will all succeed, Italian and Spanish will fail. Tried recreating the request several times, same result.

Where can I view what's wrong with the request / what the error is? I can provide the used basefile if necessary, for now I just post the id of a request that failed in my environment: 20158.

Thanks for any advice.

**Comment by RobinARH** [comment]
@ejchoGIT : Can you take a look? Thanks.

**Comment by ejchoGIT** [comment]
Hello RHaest, 
I have looked into your request ID 20158 and it was completed with error due to "Service is temporarily unavailable" status in MTHub. As far as I can see, the service is back to normal and you should be able to complete the two languages with no problem if you submit a new request. And if you use the same base (source) file and intend to translate it to two languages, you can simply select the two languages in one request before submitting. The target language selection dropdown list allows you to select multiple languages. Hope you find this tip a bit convenient. 
If you continue to see an error with your request, please send an email to dtssup@microsoft. Thanks!
