### ISSUE TITLE
GeneratePackages - ExclusionList

### ISSUE THREAD

**Issue by DiSae** [MicrosoftDocs/dynamics-365-unified-operations-public#1762]
1. Nowhere in this article it is mentioned that the 'GeneratePackages.ps1' script is used to exclude packages.
2. GeneratePackages exclusion list does not apply to model source package that is also created via the above mentioned ps1 script.
3. Maintaining the list of TestAutomation packages is very hard. Lots of build pipelines require lots of updates.
4. I'm not sure, but if you have like 100 test automation packages, the string in the ExclusionList would be immense long, isn't there a limit in characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b18b0d-ef3d-d102-77ab-5ee4acbb36bb
* Version Independent ID: b2ceda2f-086b-0d99-5c23-1b51e5ef5237
* Content: [Exclude test packages from build output - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/exclude-test-packages)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/exclude-test-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/exclude-test-packages.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by sericks007** [comment]
@DiSae, thank you for your feedback!

@jorisdg, please review the feedback and update the content as necessary.

**Comment by jorisdg** [comment]
The article does not mention the script's filename directly, but it explains which task needs to be updated if updating from a very old platform version. The step mentioned in the documentation ("generate packages") in the build definition of course shows the name of the script if one would need to know that.
In general there is no need to mention the script by name, since it is not truly meant to be customized so it's mostly irrelevant.

The other 3 comments are not documentation issues but comments and feedback on the feature itself. Since the generate packages step will long term be replaced with the new generate package task in the tools we have in the Azure DevOps marketplace, we're currently not considering changing the existing scripts. The new task works very differently using standard Azure DevOps search patterns with wildcards etc.

**Comment by DiSae** [comment]
Hi @jorisdg ,

Which new generate package task are you referring to?

When searching in the Azure DevOps marketplace I could only find tasks named 'Generate Release Notes Build Task', looking into that one it seems that it doesn't generate deployable packages.
![image](https://user-images.githubusercontent.com/31828724/67365714-6456d580-f572-11e9-8a2e-42697f794aec.png)

**Comment by jorisdg** [comment]
It's in the same extension you already have installed for the release tasks. In a build or release pipeline just search for generate packages.
Also see https://community.dynamics.com/365/financeandoperations/b/newdynamicsax/posts/azure-devops-tasks-for-packaging-and-model-versioning

**Comment by jorisdg** [comment]
We're unclear on the long-term future of AxModel (we'd like to use nuget instead at some point) but I will review with the team if we can support axmodel for the time being.
