### ISSUE TITLE
Better explanation needed

### ISSUE THREAD

**Issue by drhexgit** [MicrosoftDocs/dynamics-365-unified-operations-public#1863]
A user would not normally expect an *idle* session to cause extra load, please add explanation as to why if that is indeed the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c33ffb81-b152-64b8-01ef-6136299f0324
* Version Independent ID: dfd275dd-0249-b481-38b4-d61a617cbe6a
* Content: [Set the session idle timeout - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/session-idle-timeout.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @hasaid
* Microsoft Alias: **hasaid**

**Comment by hasaid** [comment]
An “idle” session is one that a user is not actively using, meaning there is no current request from the user. Between requests, the session is stored in the AOS for the next interaction with the user. While in this idle state, the session still holds on to system resources like memory and database connections, and this can cause the extra “load” on the system resources. Increasing the idle session timeout means that the inactive session will remain in the AOS for a longer time until it is cleaned up automatically due to inactivity.
Note: if a user closes their browser, this will end their sessions immediately and the idle session timeout does not come into play.
Freeing up session resources when not needed is recommended to make sure the system is performing for other users and is also a best practice when it comes to security.
