### ISSUE TITLE
Business event never starts

### ISSUE THREAD

**Issue by abermudezr** [MicrosoftDocs/dynamics-365-unified-operations-public#1911]
I have followed this tutorial but it doesn't run successfully, when I generate the trigger action, the event is created in Dynamics in the Active Events form, and remains there but in PowerAutomate, the flow never starts. Is there any configuration o parameter that I have to check in order to complete this functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d6f12b-8071-1e29-67e1-82d47562ee61
* Version Independent ID: e2c186f8-0701-fab1-c806-32632e8ad8b5
* Content: [Business events and workflow approvals - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/business-events/how-to/how-to-workflow.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ibenbouzid
* Microsoft Alias: **imbenbou**

**Comment by sericks007** [comment]
@abermudezr, thanks for posting here!

@Sunil-Garg, please review and update the content, as necessary.

**Comment by jyotichoudhury** [comment]
In the Business Events (SysAdmin>Setup>Business events>Business events catalog) in D365FO, delete the active event. Then click on Business events catalog, select the business event and then click 'Activate'>Specify the legal entity and the end point. And then try.

**Comment by jimhunnicut** [comment]
@Sunil-Garg, this also doesn't work for me.  Double and triple checked the sets I took.  Is this functionality actually working?

**Comment by jimhunnicut** [comment]
The timesheet workflow does not appear to support Business Events.  I am now getting the event to trigger but receive an error that states:

An error has occurred.  Exception occurred while executing action validate on Entity WorkflowWorkItem: Unable to create an instance of TSWorkflowActionManager. Please update TSWorkflowActionManager so that it implements IValidateWorkflowWorkItemAction. Please contact your System Administrator for further assistance.
clientRequestId: 9e902991-bb4a-457a-8f4c-7ffe37c1a250.  

I wonder how many workflows are troubled by this issue.  At least for the Timesheet workflow approval, the product team has not caught up with this new "feature". 

Looking forward to seeing this new "feature" to actually work correctly.  One day it will be a helpful feature.

**Comment by Sunil-Garg** [comment]
@Chris Garty<mailto:Chris.Garty@microsoft.com>

________________________________

**Comment by sericks007** [comment]
Bug 406928 has been logged to track this issue.

**Comment by NShaukat-US** [comment]
> The timesheet workflow does not appear to support Business Events.  I am now getting the event to trigger but receive an error that states:
> An error has occurred.  Exception occurred while executing action validate on Entity WorkflowWorkItem: Unable to create an instance of TSWorkflowActionManager. Please update TSWorkflowActionManager so that it implements IValidateWorkflowWorkItemAction. Please contact your System Administrator for further assistance.
> clientRequestId: 9e902991-bb4a-457a-8f4c-7ffe37c1a250.
> I wonder how many workflows are troubled by this issue.  At least for the Timesheet workflow approval, the product team has not caught up with this new "feature".
> Looking forward to seeing this new "feature" to actually work correctly.  One day it will be a helpful feature.



"To enable external completion of work items, the work item action manager class needs to implement the IValidateWorkflowWorkItemAction interface. The standard WorkflowWorkItemActionManager class has implemented this interface. In Platform update 32, the TrvWorkflowWorkItemActionManager class was updated to implement the IValidateWorkflowWorkItemAction interface. Use the existing IValidateWorkflowWorkItemAction implementations as examples to notify updates about other WorkflowWorkItemActionManager classes." Via Microsoft Docs

**Comment by Sunil-Garg** [comment]
@Chris Garty<mailto:Chris.Garty@microsoft.com>

________________________________

**Comment by sericks007** [comment]
Correction: Bug 437909 has been logged to track this issue.

**Comment by ChrisGarty** [comment]
Fixed the TSWorkflowActionManager implementation of IValidateWorkflowWorkItemAction in App AX10.0.10 via bug 406928. Please update to 10.0.10 + PU34 to get this capability.

**Comment by jimhunnicut** [comment]
Thanks guys.

Jim Hunnicut
Technical Delivery Manager
Arbela Technologies Corp.

Connect with Arbela: Website<http://www.arbelatech.com/> | LinkedIn<https://www.linkedin.com/company/arbela-technologies> | Twitter<https://twitter.com/arbelatech> | Facebook<https://www.facebook.com/arbelatech/>

Mobile:  +1 928 890 7363
E-Mail:  jim.hunnicut@arbelatech.com<mailto:jim.hunnicut@arbelatech.com>
Linkedin :  https://www.linkedin.com/in/jim-hunnicut-25940a2
Time Zone: Arizona Mountain Time (GMT -7) does not observe Daylight Savings Time

Please use the following link if you have an Arbela support contract and have a support user ID assigned
to you for your organization: http://myarbela.com<http://myarbela.com/>

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the email by you is prohibited.
