### ISSUE TITLE
   Microsoft need to offer their own b2b portal / ecommerce extension to all dynamics. 

### ISSUE THREAD

**Issue by ezbz007** [MicrosoftDocs/dynamics-365-unified-operations-public#192]
Microsoft need to offer their own b2b portal / ecommerce module in order to keep up with the coming competition. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afcb5f6-8b55-f088-5cf6-c2b8e2365701
* Version Independent ID: 7936e07d-fdb9-a548-04b1-d0e18272882a
* Content: [Online store overview - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/online-stores)
* Content Source: [articles/retail/online-stores.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/retail/online-stores.md)
* Service: **dynamics-365-retail**
* GitHub Login: @kfend
* Microsoft Alias: **meeram**

**Comment by ShylaThompson** [comment]
Thanks for taking the time to provide feedback on Finance and Operations! We recommend that you to use the Ideas site to submit it directly, because that will enable you to receive notifications, vote, and monitor the progress of your idea more closely. 

[Ideas site](https://experience.dynamics.com/ideas/list/?forum=16691718-61e2-e611-8101-5065f38b21f1)
