### ISSUE TITLE
can I have access to printers per user, so specific users can have access to only specific printers

### ISSUE THREAD

**Issue by MRasheed84** [MicrosoftDocs/dynamics-365-unified-operations-public#1931]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent?source=docs#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by josaw1** [comment]
Thank you for your question. @TJVass can you please take a look?

**Comment by josaw1** [comment]
Bug 408807 created to track issue.

**Comment by beefcake123** [comment]
The document router agent seems to always print PDFs via "Fit" instead of "Actual Size". This is causing issues on some of our official reports & documents to be scaled by the document router agent. Is there an option somewhere to change this?
Can we use the document router agent to print PDFs without using Adobe Reader? Using Chrome for example as default device to handle PDFs wouldn't rescale the document anymore.
