### ISSUE TITLE
Error: The option 4 for querystore query_capture_mode is not supported.

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#1933]
New error appearing when trying to import the bacpac to the Dev box:

*** Error importing database:Could not import package.
The option 4 for querystore query_capture_mode is not supported.

How do we get around this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5e8701-e1d4-25f8-d76a-ee7870b915e1
* Version Independent ID: 624211c7-2eb4-7154-d38f-236dc6f8f7a9
* Content: [Export a copy of the standard user acceptance testing (UAT) database](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by ubaidullah195** [comment]
I'm facing the same error on a recently exported bacpac. Can anyone suggest the solution for this?

**Comment by josaw1** [comment]
Bug 408808 created to track this issue.

**Comment by laneswenka** [comment]
This was a new azure default setting that wasn't compatible with Dev SQL Servers.  We have since updated the automation to set this explicitly on export.

**Comment by mikecaterino** [comment]
> This was a new azure default setting that wasn't compatible with Dev SQL Servers. We have since updated the automation to set this explicitly on export.

This issue still exists (as of yesterday) for bacpacs created using the Export databse from the Move database in LCS on a sandbox environment hosted utilizing the service fabric. Still had to manually update the model.xml and generate a new checksum for the bacpac.

**Comment by laneswenka** [comment]
Hi Mike!

Can you send me your environmentID? Lane.Swenka@microsoft.com

Lane

Sent from my iPhone

On Mar 20, 2020, at 9:19 AM, Mike Caterino <notifications@github.com> wrote:

﻿

This was a new azure default setting that wasn't compatible with Dev SQL Servers. We have since updated the automation to set this explicitly on export.

This issue still exists (as of yesterday) for bacpacs created using the Export databse from the Move database in LCS on a sandbox environment hosted utilizing the service fabric. Still had to manually update the model.xml and generate a new checksum for the bacpac.

**Comment by Shind44** [comment]
Hello Mike 
i have the same issue with our environnement. I send you the environnementID by mail

Charles
