### ISSUE TITLE
Risk assessment setup has invalid breadcrumbs

### ISSUE THREAD

**Issue by MMT0905** [MicrosoftDocs/dynamics-365-unified-operations-public#2162]
The document indicates to set up risk assessment to go to  (Credit management > Setup > Risk setup > Risk assessments).  It should start at Credit and Collections, not Credit management.  Additionally, there is no "Risk setup>Risk assessments" under the Set up portion of Credit Management.  Where can customer risk be added?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a07f87a-ebe3-e319-b622-0fab3c5d67a4
* Version Independent ID: 0f0ec9c2-b785-e6ad-b5ca-88f7da7ec8e9
* Content: [Credit management setup](https://docs.microsoft.com/en-us/dynamics365/finance/accounts-receivable/cm-setup-information)
* Content Source: [articles/finance/accounts-receivable/cm-setup-information.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/accounts-receivable/cm-setup-information.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @mikefalkner
* Microsoft Alias: **mfalkner**

**Comment by tonyafehr** [comment]
@mikefalkner, please review this feedback and consider making updates. Thanks!

**Comment by tonyafehr** [comment]
Reassigning to @aprilolson for review

**Comment by aprilolson** [comment]
Can you assign this to @Pat Nolte<mailto:Patrick.Nolte@microsoft.com>? He is the owner of credit management now.

April Olson
Dynamics 365 Finance
Principal Group Product Manager
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexible work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until it’s convenient for you.

**Comment by panolte** [comment]
This was completed as part of an update in October 2020.
