### ISSUE TITLE
Please upddate this document so that it will not give the wrong guidance about switching on/off the maintenance mode in non-prod env. 

### ISSUE THREAD

**Issue by baiy206** [MicrosoftDocs/dynamics-365-unified-operations-public#217]
Below command in this article is said to be not working any more as per below article. Please update accordingly.
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/vms-no-admin-access#can-the-system-be-put-into-maintenance-mode

J:\AosService\PackagesLocalDirectory\Bin\Microsoft.Dynamics.AX.Deployment.Setup.exe --metadatadir J:\AosService\PackagesLocalDirectory --bindir J:\AosService\PackagesLocalDirectory\Bin --sqlserver . --sqldatabase axdb --sqluser axdbadmin --sqlpwd ********* --setupmode maintenancemode --isinmaintenancemode true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2a8d7e-56e8-2ef5-b7a1-4ccf54a6ce1e
* Version Independent ID: 985efdc1-7b47-ad77-4eb9-7bd940547843
* Content: [Maintenance mode - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by ShylaThompson** [comment]
Bug logged: 229523

**Comment by okayakdeniz** [comment]
Batch services is being stopped in Non-Production environment after maintenance mode to set turning on.

**Comment by skaue** [comment]
It should be emphasized that when Maintenance Mode is turned on (enabled), the Batch service will not start (by design). This will also block any servicing of the environment, as those expect the stop/start of batch to be part of the process (runbook). So turning off Maintenance Mode when the configuration is changed is extremely important. 

Also, when switching this mode on/off, the AOS/IIS needs to restart obviously. So anyone simply changing the SQL value directly and not running the tool (for example on a VM without local admin), they must restart the service to refresh the setting, as it is cached.
