### ISSUE TITLE
Report Deletions and Expirations

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/dynamics-365-unified-operations-public#2276]
I'm trying to put this whole story together for this new feature. It's in this article under v10.0.7 but in the What's New for 10.0.8. I don't see anything in Feature management related to this (but I'm looking at v10.0.10 preview so maybe the feature management piece is gone?).

In addition, it's not clear how the feature works. Are these parameter settings inside the FR report definition or inside of F&O? Is the user allowed to change the retention policy, or they are only allowed to switch between 90 days and Never (it says "Currently" these are the options - like currently before this new update or currently after this update)? There's a new duty which suggests this applies to an F&O setup table, but I didn't see anything in GL parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039e1ed0-5b6b-04b9-4a76-9588eeeefc65
* Version Independent ID: 0c019c41-e6b1-2ae6-89e5-cd4cddef1d3f
* Content: [Financial reporting overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-reporting-getting-started#report-deletions-and-expirations)
* Content Source: [articles/finance/general-ledger/financial-reporting-getting-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/financial-reporting-getting-started.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
Thanks for the feedback. 
@aprilolson and @rschloma please review.

**Comment by ryansandness** [comment]
Thanks for the feedback. I will provide an update clarifying this was 10.0.8, not 10.0.7. The feature name is **Financial report retention policies**, but you have to look in the "All" tab since it is mandatory. 

We've released the functionality with two options, but will certainly consider adding more as we get feedback. There is already an idea on experience.dynamics.com you are welcome to add feedback and options, like on a per-report basis as you mentioned.
