### ISSUE TITLE
This feature is forced for all the users that will use "Ship all products and Ship selected products".

### ISSUE THREAD

**Issue by maismail87** [MicrosoftDocs/dynamics-365-unified-operations-public#2408]
There is no way to turn of/on this feature which will give all the users with access to "Ship all products and Ship selected products" POS operation the ability to select different location to ship item from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65cfaa02-4ac6-b282-5df5-b2ee9cf493c1
* Version Independent ID: fb35efd9-56fa-5a38-90cf-6b67e6ec1ee1
* Content: [Ship orders from another store by using the Charge send feature - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/charge-send#feedback)
* Content Source: [articles/commerce/charge-send.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/commerce/charge-send.md)
* Service: **dynamics-365-retail**
* Product: ****
* Technology: ****
* GitHub Login: @ashishmsft
* Microsoft Alias: **asharchw**

**Comment by josaw1** [comment]
Thank you for your feedback. @ashishmsft can you please review?

**Comment by josaw1** [comment]
BUG 451926 created to track this issue.

**Comment by hhainesms** [comment]
If the organization has deployed the Ship All and Ship Selected operations for their POS devices, then yes, all users can use the "change origin" function to change the location of shipping - this is by design.  If there is a desire to only allow change origin to be done by certain users - I would suggest putting a product suggestion on the https://experience.dynamics.com/ideas/  site.
