### ISSUE TITLE
Redeploying or restarting the runtime on the VM

### ISSUE THREAD

**Issue by JameZJ** [MicrosoftDocs/dynamics-365-unified-operations-public#2421]
Open File Explorer, and go to C:\CustomerServiceUnit.
Right-click AOSDeploy.cmd, and then click Run as administrator.

C:\CustomerServiceUnit does not exist on my VM.

**Comment by tonyafehr** [comment]
Thanks for contacting us. If there's a specific topic that needs to be updated, please provide the topic name. Otherwise, we're unable to handle Support requests for the product on this site. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by JameZJ** [comment]
Here is the link to the topic: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/access-instances#redeploying-or-restarting-the-runtime-on-the-vm

C:\CustomerServiceUnit does not exist on my VM.

**Comment by tonyafehr** [comment]
@laneswenka, for visibility.

**Comment by JameZJ** [comment]
Any update on where AOSDeploy.cmd is located if that folder doesn't exist?

**Comment by laneswenka** [comment]
Please assign to DevTools team, this article isn't related to LCS / Admin / environment management
