### ISSUE TITLE
Power Platform considerations

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#2427]
Hi
When we have an D365 Finance and Supply Chain Management system and we are using Dual Write I believe there is an impact if the database refresh is undertaken. I believe that everything needs to be stopped and upon post-refresh all the re-linking is undertaken. I am not sure if there are other considerations with CDS or the Power Platform but I feel the consideration for Dual Write should be called out because if you do not stop the link then the database refresh will corrupt the environments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
* Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
* Content: [Refresh database - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh)
* Content Source: [articles/fin-ops-core/dev-itpro/database/database-refresh.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by laneswenka** [comment]
Hi Steven!

We delete the CDS link tables during refresh so that UAT cannot talk to your CDS instance. You will need to manually relink to another CDS after refresh.

Lane

Sent from my iPhone

On May 21, 2020, at 3:08 AM, Steven Weaver <notifications@github.com> wrote:

﻿

Hi
When we have an D365 Finance and Supply Chain Management system and we are using Dual Write I believe there is an impact if the database refresh is undertaken. I believe that everything needs to be stopped and upon post-refresh all the re-linking is undertaken. I am not sure if there are other considerations with CDS or the Power Platform but I feel the consideration for Dual Write should be called out because if you do not stop the link then the database refresh will corrupt the environments.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 9d28e8cc-5110-f01b-db76-94479ec2fa91
  *   Version Independent ID: f0710707-9ff2-84a1-30c7-1f0d44e3a0d7
  *   Content: Refresh database - Finance & Operations | Dynamics 365<https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/database-refresh>
  *   Content Source: articles/fin-ops-core/dev-itpro/database/database-refresh.md<https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/database/database-refresh.md>
  *   Service: dynamics-ax-platform
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @laneswenka<https://github.com/laneswenka>
  *   Microsoft Alias: laneswenka

**Comment by weaveriski** [comment]
Hi Lane

All good thanks, I hope you are keeping well.

My understanding is that if you don’t stop the CDS links and then do a refresh the system gets into a horrible position. This is feedback from the technical team on the process after they encountered this earlier this year trying to refresh the DB side of the process. On the DB refresh there is no reference to this, but I feel there should be if it is an issue, but perhaps I am misinterpreting the issue.

Are you saying that today a database refresh in a Dual Write configured environment is not an issue because the process now deletes the CDS links (even when running/connected), and there is a manual relink required, but no corruption of the FO instance as we encountered?

I can loop back in with the technical team to check again if that is the case?

I am trying to configure Dual Write and setup a checklist or considerations document for environment creation and management – I was told this was an issue by the team that previously tried to get it working 😊

Steve

**Comment by laneswenka** [comment]
In a refresh with a dual write linked source and a non linked target, there shouldn’t be any issue.

We copy the source AXDB, delete its CDS tables which tell it how to talk to CDS, cleanup SMTP settings and so forth like normal, and then replace the AXDB in the target with it.

Now if your target is also linked to another CDS, it is possible you will want to unlink it prior so that it doesn’t continue to receive data that isn’t aligned.

If you have an ActivityID from a refresh that had issues please feel free to email me and we can investigate!  But in the simple scenario above it shouldn’t be an issue.

Lane

Sent from my iPhone

On May 21, 2020, at 5:30 AM, Steven Weaver <notifications@github.com> wrote:

﻿

Hi Lane

All good thanks, I hope you are keeping well.

My understanding is that if you don’t stop the CDS links and then do a refresh the system gets into a horrible position. This is feedback from the technical team on the process after they encountered this earlier this year trying to refresh the DB side of the process. On the DB refresh there is no reference to this, but I feel there should be if it is an issue, but perhaps I am misinterpreting the issue.

Are you saying that today a database refresh in a Dual Write configured environment is not an issue because the process now deletes the CDS links (even when running/connected), and there is a manual relink required, but no corruption of the FO instance as we encountered?

I can loop back in with the technical team to check again if that is the case?

I am trying to configure Dual Write and setup a checklist or considerations document for environment creation and management – I was told this was an issue by the team that previously tried to get it working 😊

Steve

**Comment by weaveriski** [comment]
Hi Lane

This is our scenario – test is connected via dual write to a test CDS. We refresh from Prod. If we don’t unlink the Test Dual Write first,  dual write breaks and we needed to involve Microsoft support.

We also did a Point in Time restore to an environment with Dual Write connected and it made the environment unusable.

It is just a warning for scenarios that mean your environment ends up being unusable and you need to engage with Microsoft support, just looking to share that pain 😊

Steve

**Comment by laneswenka** [comment]
This should not be the case but I am following up.  So your source is not linked correct? Just the target?

**Comment by laneswenka** [comment]
Also could you provide me an ActivityID or EnvironmentID where this has failed so that we can review?

**Comment by weaveriski** [comment]
Hi Lane

The environments no longer exist.

In summary for the context of this the page was “refreshing the DB”, If the target environment has Dual Write enabled, and we plan to replace the database (via restore in time, or restore from another database) then stop and unlink the entities first. Should that reference be made somewhere on the refresh database page to try and stop users hitting issues with the process when Dual Write is in the mix?

The technical team referenced you in response to my question for more information without knowing it was you I was talking to! You are aware of the process and asking how people are getting around it, I am just suggesting a reference on the refresh DB might be useful, but I will leave it up to you, feel free to close the request 😊



[cid:image001.png@01D63449.3340CCB0]


This is the  closest I could find now – there must have been something else in Yammer but I can’t get it now. Instruction boiled down to stop Dual Write before you replace the database from any source. And it made sense. Even if you do Point In Time restore you have to consider for every entity whether a new bulk update from X to Y is required after the update.


Oh – and update from Lane
[cid:image002.png@01D63449.3340CCB0]

https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=684447363579904&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&group_ids=16038053&search=copy%20database
