### ISSUE TITLE
Correct explanation of use of Nuget and a pipeline

### ISSUE THREAD

**Issue by jansenrf** [MicrosoftDocs/dynamics-365-unified-operations-public#2435]
Can I use a new pipeline for the build instaed of using the pipeline to the old build server?

And do you have a better step by step installation document for these solution with Nuget?

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation?github-auth-complete=true#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment]
@jorisdg, please review. Thanks!

**Comment by jorisdg** [comment]
You can use the new build pipeline instead of the one that comes with the build VM. Keep in mind of the limitations though (no SysTest or DBSync). Since the new pipeline doesn't cost you anything to try, you can figure out if you like this or not.
We don't have more step by step and we're actively trying to avoid creating documentation for Azure DevOps features - hence the links to AZDO docs. There are some really good articles from the community out there though that contain step by step instructions.

You can always connect on the community.dynamics.com to ask questions.
