### ISSUE TITLE
Inventory on-hand service part of this release?

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#2540]
I see Inventory on-hand service as part of this release. When I click on it, I go to a page where nothing can be read about the on-hand service. So is this still part of the release or is the target page not up-to-date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fbf986-9cf0-80de-795f-68d79a581b5e
* Version Independent ID: aa3e520b-3fd5-c196-4679-f8f0a217c626
* Content: [What's new or changed in Dynamics 365 Supply Chain Management 10.0.12 (August 2020) - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-scm-10-0-12)
* Content Source: [articles/supply-chain/get-started/whats-new-scm-10-0-12.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/get-started/whats-new-scm-10-0-12.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by kamaybac** [comment]
Hi @JeroenLeeflang , thank you pointing out this broken link. I looked into it and discovered that the feature has unfortunately been delayed, so it has been removed from the release plan, and that's why the link doesn't work. We have not yet announced a new release date for this feature. I will remove this feature and link from the release announcement.
