### ISSUE TITLE
Cannot make db sync

### ISSUE THREAD

**Issue by dynanac** [MicrosoftDocs/dynamics-365-unified-operations-public#2614]
Hi,

I tried to perform database synchronization but I got access denied.

How can I resolve this issue ? Because I can't upgrade if I don't make it work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0d2c68-08ea-77b8-af74-cd889a8344ca
* Version Independent ID: d88b6646-49de-f7eb-3d7c-7d1e700131e1
* Content: [Upgrade data in development or demo environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update#before-you-begin)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
DbSync can be run from Visual Studio on Developer machines. Did you try that method?

Sent from my iPhone

On Jul 22, 2020, at 2:25 AM, dynanac <notifications@github.com> wrote:

﻿

Hi,

I tried to perform database synchronization but I got access denied.

How can I resolve this issue ? Because I can't upgrade if I don't make it work

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: fe0d2c68-08ea-77b8-af74-cd889a8344ca
  *   Version Independent ID: d88b6646-49de-f7eb-3d7c-7d1e700131e1
  *   Content: Upgrade data in development or demo environments - Finance & Operations | Dynamics 365<https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update#before-you-begin>
  *   Content Source: articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md<https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/upgrade-data-to-latest-update.md>
  *   Service: dynamics-ax-platform
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @laneswenka<https://github.com/laneswenka>
  *   Microsoft Alias: laswenka
