### ISSUE TITLE
Extend scale property

### ISSUE THREAD

**Issue by ELandAX** [MicrosoftDocs/dynamics-365-unified-operations-public#264]
Hi,

How could we extend Scale property of Real EDTs e.g. RealBase? In AX 2012 it was 16 decimals by default and that was enough, but in D365 it is changed to 6(!). It creates us problems as in our solution amounts are calculated incorrectly due to Qty precision being only 6 decimals.

**Comment by sericks007** [comment]
Thanks for posting your question.  We do have this topic published: "Modify an extended data type" (https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/modify-edt).  Please let us know if this topic answers your question.  If not, I'll log this content request.

**Comment by ELandAX** [comment]
Hi Sally,

Thanks for a quick response.

I have read this but it did not help.
It does not say anything about Scale property and I tried everything I know
in practice. Did not work.

Respectfully,
Evaldas L.

2018-07-19, kt 22:10, Sally Erickson <notifications@github.com> rašė:

**Comment by sericks007** [comment]
Hi Evaldas. I checked with the engineering manager, and he said the platform currently doesn't support extending Scale -- only number of decimals.  He recommended that you ask for an extension so that we can prioritize adding this capability.  Please see our "Extensibility requests" article: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-requests
