### ISSUE TITLE
Extension naming of table extenstion

### ISSUE THREAD

**Issue by PalleAgermark** [MicrosoftDocs/dynamics-365-unified-operations-public#2747]
When I create a new table extension it is named OrigName.[Model]. Your guidelines here say it should be named OrigName.[Model]**Extension**. Why is the VS tooling not following the guidelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb14aee-fcc5-0b16-5e98-2b30febdce76
* Version Independent ID: d2e11166-cd39-ee9c-d27d-d85e23906c76
* Content: [Naming guidelines for extensions - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/extensibility/naming-guidelines-extensions.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @LarsBlaaberg
* Microsoft Alias: **pvillads**

**Comment by jorisdg** [comment]
I will update the doc. We don't care about the name as long as it's not just "extension" but something unique enough. That was changed in the tooling in 2018 or 2019 so it doesn't just default to .extension, .extension1, .extension2 etc. as this could and has resulted in name clashes. Since model names are unique, the .[_ModelName_] default is perfectly acceptable, and so is .ModelExtension (it's just longer).
