### ISSUE TITLE
Paragraph 7 appears to be missing an illustration/image

### ISSUE THREAD

**Issue by mburbackeoc** [MicrosoftDocs/dynamics-365-unified-operations-public#2764]
Hello - as I have been reading this page - I believe there is an image missing at Paragraph 7.  
thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edfe78b-6486-5678-a171-95f81d2715ef
* Version Independent ID: 62a24546-bb3f-5194-43f0-0db144643ab7
* Content: [Phantom items - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/phantom-items)
* Content Source: [articles/supply-chain/production-control/phantom-items.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/supply-chain/production-control/phantom-items.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ShylaThompson
* Microsoft Alias: **shylaw**

**Comment by josaw1** [comment]
Thanks for the feedback. @kamaybac can you please take a look?

**Comment by josaw1** [comment]
BUG 510661 created to track this issue.

**Comment by kamaybac** [comment]
All the required images were present, but some were positioned incorrectly. They were also difficult to refer to from the text due to lack of figure numbers/captions. We repositioned the images, added numbers/captions, and used the figure numbers to make it more clear which image the body text was talking about in each instance.
