### ISSUE TITLE
Typos in Troubleshooting issues opening Report Designer section

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2785]
The page says "Workstations are required to install Visual Studio .NET 4.6.2 or higher." This should instead say "Workstations are required to install Microsoft .NET Framework 4.6.2 or higher."

Also, please make the text "This version of the Microsoft .NET Framework can be downloaded and installed from the Microsoft Download Center." on the same bullet point line with the bullet point for .NET. Having this on its own line without a bullet point makes it difficult to read, and separates the next bullet point from the rest of the items in the related list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039e1ed0-5b6b-04b9-4a76-9588eeeefc65
* Version Independent ID: 0c019c41-e6b1-2ae6-89e5-cd4cddef1d3f
* Content: [Financial reporting overview - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/financial-reporting-getting-started#troubleshooting-issues-opening-report-designer)
* Content Source: [articles/finance/general-ledger/financial-reporting-getting-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/finance/general-ledger/financial-reporting-getting-started.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by tonyafehr** [comment]
@jopankow, great feedback. I updated this topic and changes will be live tomorrow. Thank you!

**Comment by aprilolson** [comment]
Adding @Jinnie Wong<mailto:jiwo@microsoft.com> as new PM for financial reporting.

Josh is our Senior Support Engineer for Financial reporting so I approve this if it came from him.
@Josh Pankow<mailto:jopankow@microsoft.com> are you able to directly add this yourself? It’d be good to allow Senior CSS to update these.

April Olson
Dynamics 365 Finance
Principal Group Product Manager
Check out our Dynamics 365 Finance blog<https://community.dynamics.com/365/financeandoperations/b/dynamics-365-finance-blog>.

Our workplace allows for a flexible work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until it’s convenient for you.
