### ISSUE TITLE
Cleanup of warning() messages

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#2836]
Regarding following paragraph in the documentation: 

> Because of the way that the system handles the cleanup of validation messages, when the warning() or checkFailed() API is used, the return value of validate() should always be set to false. Otherwise, warning messages might not be shown to the user.

I have the problem currently that warning messages are not shown to the user because of the above. Which validate() method is meant here? What should return false so that the warnings aren't cleaned up? 

If I replace warning() with info() or error(), the messages are shown properly, but it is per definition a warning needed at that point as the user should be warned about the current data but be able to proceed with the process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1e41d9b-94da-8f10-532e-b0507ae09164
* Version Independent ID: 6d385db4-d3c9-d8be-6bf1-d420803303f0
* Content: [Messaging system for Finance and Operations apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/messaging-user)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/messaging-user.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/user-interface/messaging-user.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment]
@SysC0mp, thanks for providing this feedback.

@jasongre, please review and update the content, as needed.

**Comment by sericks007** [comment]
Bug 516461 has been logged to track this issue.

**Comment by jasongre** [comment]
@SysC0mp See this section for more details on the behavior of when warning messages are cleaned up automatically if the warning is defined in the validate() method of the control, field, or table: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/messaging-user#when-are-validation-messages-cleaned-up. Validate() should return false to signify that validation of the record's current values failed. If validate returns true, that means there were no issues and no warnings will be shown (because the existing warnings are cleaned up).
