### ISSUE TITLE
Print Management values removed during upgrade

### ISSUE THREAD

**Issue by jopankow** [MicrosoftDocs/dynamics-365-unified-operations-public#2907]
The Print Management section (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/app-validation-process#print-management) does not include information that the Print Management values are removed during the AX 2012 to D365 upgrade.

A customer would like to have documentation stating this is the expected behavior. If this is expected, the customer would also like documentation on how the settings can be migrated from AX 2012 to D365 as they have hundreds of records that need to be migrated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddeaa1c4-83ed-b81a-263b-cc3d5d0fa2d7
* Version Independent ID: cdb9ed8c-ead4-a3c8-63a5-85bdbc9a66cb
* Content: [Upgrade from AX 2012 - Post-upgrade tasks - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/app-validation-process#print-management)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/app-validation-process.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/migration-upgrade/app-validation-process.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Print management settings should not be lost as part of upgrade.  Those settings however are deleted whenever a database import or refresh is performed, so it would be important that your upgrade followed the steps as outlined here so that you can upgrade directly against your Sandbox environment:
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/replication-setup

@sericks007 this can be resolved.  If customers are seeing their data deleted during upgrade script execution we should file a bug on F&O app team or at minimum open a support case.
