### ISSUE TITLE
What binaries are overwritten from the dev/build environment?

### ISSUE THREAD

**Issue by andi-meier** [MicrosoftDocs/dynamics-365-unified-operations-public#2933]
I don't understand this statement on that page:

Make sure that the Application binary update package is applied to your dev/build environment before it is applied to your sandbox and production environment - If the application binary package is applied directly to your Tier 2+ sandbox environment but is not applied on your dev/build environment, the next time you move an AOT package from dev/build box (which does not have the same application binaries as your sandbox environment) to sandbox, some of the application binaries will be overwritten with what is in your dev/build environment. This could result in a regression of the version of your sandbox environment.

What binaries are overwritten from the dev/build environment?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcf4a74-1317-2f29-a9a6-3eb4c20c431f
* Version Independent ID: 9ce93e91-c55a-708b-bc9c-95a34bbf5b7b
* Content: [Apply updates to cloud environments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/apply-deployable-package-system.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by tonyafehr** [comment]
@andi-meier, thanks for the feedback. 
@laneswenka, please review.

**Comment by tonyafehr** [comment]
Bug 527681 logged to track this issue.

**Comment by laneswenka** [comment]
This doesn't sound correct - @jorisdg  could you confirm that is not valid?  Customers build environment should always be equal to or older than the target Sandbox/Production environments.  And because we don't allow overlayering, the risk of moving binaries from a customer's customization package from build -> Sandbox -> Prod should not be happening.

**Comment by jorisdg** [comment]
This is wrong and even with over-layering would be wrong. If nothing else, LCS will plain refuse to deploy the package if it's coming from a newer version. There are no "files copied" other than the X++ binaries you're trying to deploy, otherwise backward compatibility wouldn't work either.

I agree with your proposed statement that dev/build should be equal or older for compatibility. The statement about files being copied should be entirely removed.

**Comment by laneswenka** [comment]
Changes are in PR, thanks for the quick confirmation @jorisdg !
