### ISSUE TITLE
Links to 10.0.19 and 10.0.20 are missing

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#3412]
In the list, links to 10.0.19 and 10.0.20 are missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c023fc2-87cd-c17b-5578-dc830ab6b015
* Version Independent ID: 73ff0eda-6e9c-f859-da8a-01acf5c31908
* Content: [What's new or changed in Dynamics 365 Supply Chain Management - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/get-started/whats-new-home-page)
* Content Source: [articles/supply-chain/get-started/whats-new-home-page.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/get-started/whats-new-home-page.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @kamaybac
* Microsoft Alias: **kamaybac**

**Comment by kamaybac** [comment]
@DKobayashi-ykgw , thanks for getting in touch. This page only lists versions that are generally available, which is why the preview releases (10.0.20 and, until today, 10.0.19) are not listed here (though they are shown in the left-column navigator). I will be adding the link to 10.0.19 later today.
