### ISSUE TITLE
Please provide the Platform Update version along with the app version

### ISSUE THREAD

**Issue by sbredallMCA** [MicrosoftDocs/dynamics-365-unified-operations-public#3468]
Why wouldn't you provide the PU along with the application version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ShellyBakke
* Microsoft Alias: **smiller**

**Comment by ShellyBakke** [comment]
We have moved to OneVersion number schema which combines the Application and Platform.   We used to reference the platform separately a while back when version 7.x was still supported as we did ship a separate platform for that version.   Since that is no longer supported we are only referencing and shipping OneVersion.
