### ISSUE TITLE
Install a new add-in does not appear.

### ISSUE THREAD

**Issue by kesun1** [MicrosoftDocs/dynamics-365-unified-operations-public#3538]
[Enter feedback here]
Hi,

I have set up a few env with PowerPlatform integration, but all did not have "Install a new add-in" in environment add-ins under Power Platform integration tab. If it needs something like license matter, please mention it . Thanks. 

Best regards,
Keisuke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b247a8-1e40-07d0-f44b-46f3f362a02d
* Version Independent ID: 09725d7e-90ea-f6a9-3edb-28ff4bcc7510
* Content: [Microsoft Power Platform integration with Finance and Operations apps - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/overview#enabling-the-microsoft-power-platform-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@***@***.***> can you have a look pls?
________________________________
From: kesun1 ***@***.***>
Sent: Monday, August 30, 2021 5:07:02 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Install a new add-in does not appear. (#3538)


[Enter feedback here]
Hi,

I have set up a few env with PowerPlatform integration, but all did not have "Install a new add-in" in environment add-ins under Power Platform integration tab. If it needs something like license matter, please mention it . Thanks.

Best regards,
Keisuke

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 39b247a8-1e40-07d0-f44b-46f3f362a02d
  *   Version Independent ID: 09725d7e-90ea-f6a9-3edb-28ff4bcc7510
  *   Content: Microsoft Power Platform integration with Finance and Operations apps - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Foverview%23enabling-the-microsoft-power-platform-integration&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250406143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nXO7NJV8TMH2t8k8sT50kTTxA%2Bbj6J2FIyOMHUiUMro%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/power-platform/overview.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Foverview.md&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250416102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DF9AX%2F9VWWHjw4swD1%2FvgXhBPsehQ%2Fa4Z0I2TpSLqWU%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250416102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nWYFw7eQBbticz2o9j8SyfMraTO7U5mXuiH0agJEIUI%3D&reserved=0>
  *   Microsoft Alias: sunilg

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3538&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250426055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1LPkWZYae0DrqIjS2Sth7MmHLWByA%2BaFL9b1efzW0zw%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHNKDW3I6OATTOFY4V2LXP3T7NX6LANCNFSM5DBXIY4A&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250426055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9L08R6jED6SNZZP2a0WAPrqZGS7XzvBezPKsxWrVllw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250436016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FOcqqiAnUo25QKukrONk44iF%2FpkYdibNJSUGGIhkFtE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csunilg%40microsoft.com%7Cca6a692395bf4e100f0908d96baead87%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637659220250436016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oKb%2BdT0Y%2BPt2tqta0zExhLZbmPViOcJtmbmaTehNsfs%3D&reserved=0>.

**Comment by Sunil-Garg** [comment]
Hi Keisuke,

This sounds like a support issue.  Add-ins should be available on all Tier2+ and Production environments that have Power Platform Integration completed.

Regards,
Lane

**Comment by kesun1** [comment]
Hi Lane,

Thanks. Understood. Most of my env are Tier 1. For them, that’s the reason why I did not see “Install a new add-in” in there.
However, one of them is Tier 2 sandbox. One reason for it might be that I am not admin role in the project (I found architecture role assigned to me). If it is, would it be better to mention the role (also tier2+) that can see and use “Install a new add-in” under Power Platform Integration tab? Please kindly let me know. Thanks.

Best regards,
Keisuke

Keisuke Koshin | 甲神　圭亮 | Cloud Solution　Architect | Dynamics 365 Finance, SCM, Commerce & Project Operations | Global Partner Solutions | Microsoft Japan Co., Ltd. | DD: +81 (0)3 4535 3649

本メール（添付文書を含みます。以下同じ）は情報提供のみを目的としており、本メールに記載されている情報は、本メール送信時点でのマイクロソフトの見解を示したものです。状況等の変化により、内容は変更される場合があります。本メールに表記されている内容（提示されている条件等を含みます）は、貴社との有効な契約を通じて決定されます。それまでは、正式に確定するものではありません。従って、本メールの記載内容とは異なる場合があります。また、本メールに記載されている価格はいずれも、別段の表記がない限り、参考価格となります。貴社の最終的な購入価格は、貴社のリセラー様により決定されます。マイクロソフトは、本メールの情報に対して明示的、黙示的または法的な、いかなる保証も行いません。
© 2021 Microsoft Corporation. All rights reserved.
