### ISSUE TITLE
subscriptions be active on both tenants 

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-unified-operations-public#3566]
Good day!

i just want some clarifications regarding the phrase "subscriptions be active on both tenants". in our case, our customer has an active tenant where their D365 subscriptions are currently under. now that they are starting to do an implementation on a new tenant, since subscriptions be active on both tenants, does this mean that they need to purchase new licenses on the new tenant? is there any other solutions aside from paying for a new sets of licenses? can they use a trial version of Dynamics 365? according to our technical team, the implementation will last for 2-3 months. Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60834f9-1f56-c5fc-406c-552616feca48
* Version Independent ID: d5fa1d78-e6ee-efe8-88f8-a893069e56ea
* Content: [Move LCS implementation projects to different Azure AD tenants - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant?toc=/dynamics365/commerce/toc.json)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
@jlabustro – yes, in order to move an implementation of Dynamics 365 Unified Operations apps to a new tenant, the customer will need to have the required minimum number of active subscriptions on that tenant. A trial license will not be an option. There are multiple ways in which the customer can obtain active subscriptions. If you have further project-specific questions, I recommend that you open a support ticket.

Kind regards,


***@***.***

Claudia Betz-Haubold | Principal Solution Architect | office:  +49.89.3176.2804

Please note: I am working part-time. Usual working days are Monday, Tuesday, Thursday.
Preferred meeting times: between 9 am and 6 pm CET (UTC +1).
***@***.***
Download the Implementation Guide Here!<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FD365ImplementationGuide&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C8bc2553bbc794bfedf4508d91a04c2ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637569430062120864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DtCtUiw%2FTCgZr%2BzVwhobq0jkLDBVh2Yj3eRuwsuh%2FdM%3D&reserved=0>
We work flexibly at Microsoft. If you receive an email from me outside of your normal business hours, I’m sending it at that time because it suits me. I’m not expecting you to read or reply until YOUR normal business hours. Thank you for your understanding.





From: jlabustro ***@***.***>
Sent: Monday, 13 September 2021 12:01
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Claudia Betz-Haubold ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] subscriptions be active on both tenants (#3566)


Good day!

i just want some clarifications regarding the phrase "subscriptions be active on both tenants". in our case, our customer has an active tenant where their D365 subscriptions are currently under. now that they are starting to do an implementation on a new tenant, since subscriptions be active on both tenants, does this mean that they need to purchase new licenses on the new tenant? is there any other solutions aside from paying for a new sets of licenses? can they use a trial version of Dynamics 365? according to our technical team, the implementation will last for 2-3 months. Thanks in advance

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: c60834f9-1f56-c5fc-406c-552616feca48
  *   Version Independent ID: d5fa1d78-e6ee-efe8-88f8-a893069e56ea
  *   Content: Move LCS implementation projects to different Azure AD tenants - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Ffin-ops%2Fget-started%2Fmove-lcs-implementation-project-tenant%3Ftoc%3D%2Fdynamics365%2Fcommerce%2Ftoc.json&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530588716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fmY6m%2FZhKLSpIihSs2JzsHSrs1Xv5H%2FOY%2Fgh2sj4%2B7w%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/fin-ops/get-started/move-lcs-implementation-project-tenant.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Ffin-ops%2Fget-started%2Fmove-lcs-implementation-project-tenant.md&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530598670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i4I3JjsJavp5OrITkVZMVMBogj7zfs%2FNNZw7Zp6tx1I%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @ClaudiaBetz-Haubold<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClaudiaBetz-Haubold&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530598670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ph9L0yraXChYFbGWxQvplSQCPDeZOluTuzw9W%2BhBU7U%3D&reserved=0>
  *   Microsoft Alias: chaubold

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3566&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530608629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6wV8w7CyA240f5gEnUwvn3TCecmY5UwYuewWffsnLBs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGZ6W762TJBIIP4J4SBU2PLUBXDVBANCNFSM5D5N5LIQ&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530608629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rpX2wyav1lr5Zx869cNPadxxVfz8fC33pZGDh6P7T3s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530618583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HMmNFtJWBZ%2FvENZZI1ZbSCKgwznrFuyS1vU87h1OcYc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C6caa5afa66f9405e9f0b08d9769d5d07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671240530618583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YcgGGlSn0bRD%2FRYEZ6Ul7atB8X6Rbz53bm90lyiMxHQ%3D&reserved=0>.

**Comment by jlabustro** [comment]
Hello Claudia,

Thank you for your quick response. In the multiple ways to obtain active subscription that you mentioned below, what are these ways? In this way, is there an option not to pay for another set of subscriptions?

Or as these subscriptions are required active to both tenant during the implementation process, do they need to buy or pay for these subscriptions?


Warmest regards,

JOVEL LABUSTRO
Team Lead - Licensing
Hitachi Solutions Asia Pacific
D: +63 (2) 8823-1672 | C: +63 (998) 474-5444
E: ***@***.******@***.***>

[Hitachi Solutions logo]

[Hitachi Solutions LinkedIn]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fhitachi-asia-pacific&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799093644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=97L2sysPuSoiomO7y%2FNwQrnCmkEYZmzcOWdtIKIzI%2FM%3D&reserved=0> [Hitachi Solutions Twitter] <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fhitachisolapac&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799103641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RvMnmVzTi%2B7oLNXm2QWv52FvYzvT9MS22cvu298IN0s%3D&reserved=0>   [Hitachi Solutions Facebook] <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FHitachiSolutionsAPAC&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799103641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=abwtld34EckHctso4%2BcjzGa9XlyHWwfCNB4plIdynrg%3D&reserved=0>   [Hitachi Solutions Instagram] <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fhitachisolutionsapac%2F&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799113635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P4fmYITi3fkIGpi6o7vjYzDSiiOhX%2FQNOUQzh09sa6E%3D&reserved=0>   [Hitachi Solutions YouTube] <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCEjOyglyM9RGku_Aba4rI7g&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799113635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4lvhA5Io9xO2oVglbH1jJl5iXZhEoW1BWG%2FYXHNN8js%3D&reserved=0>   [Hitachi Solutions Medium] <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2Fhitachisolutions-braintrust&data=04%7C01%7Cjlabustro%40hitachisolutions.com%7C080dc58ccdf34545401508d963b94d47%7Ce85feadf11e747bba16043b98dcc96f1%7C0%7C0%7C637650469799113635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FlnpM968UQuiQxuqyzaCSJMSolm%2Fpu9524jootR0CiM%3D&reserved=0>
