### ISSUE TITLE
About user in Dynamics Lifecycle Services service connection

### ISSUE THREAD

**Issue by Beelzenef** [MicrosoftDocs/dynamics-365-unified-operations-public#3574]
About this paragraph on [Create an LCS connection in Azure Pipelines](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection):

> Create the Dynamics Lifecycle Services service connection
>[...]
> * Username – Provide the email alias for the user credentials.
> * Password – Provide the password for the user credentials.

I am researching on this topic, about the user and password, and I have some questions:

- Can this user have MFA enabled?
- Where can I find the permissions assigned to this user?
- What permissions should this user have in a tenant and/or Azure subscription?
- Could this user be a service principal? Why is it not a service principal? 

I will be waiting for your reply, have a good day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3402c27-86a5-02f6-da5e-c49a614b2e67
* Version Independent ID: a574bc29-b33c-8eeb-ca04-983e6e08f7ea
* Content: [Create an LCS connection in Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by jorisdg** [comment]
Please review the second NOTE section in the documentation. LCS does not support service-to-service (service principal) authentication. And because the service doesn’t run interactively, MFA is not supported.

The permissions needed depend on what you’re going to use this connection for. Whichever action you perform, the user setup should have that permissions (e.g. to deploy code, this account needs to be able to deploy code… to upload to the azure library, etc.)

As far as tenant and Azure subscription, this is not relevant. This is setup for a connection to LCS, not Azure.



From: Elena.NET ***@***.***>
Sent: Monday, September 20, 2021 6:46 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Joris de Gruyter ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] About user in Dynamics Lifecycle Services service connection (#3574)


About this paragraph on Create an LCS connection in Azure Pipelines<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fdev-tools%2Fpipeline-lcs-connection&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805797407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8sEhJSzjc2dMKO3rUMVKpFlmi8sN2d9dWoJajb4M2zY%3D&reserved=0>:

Create the Dynamics Lifecycle Services service connection
[...]

  *   Username – Provide the email alias for the user credentials.
  *   Password – Provide the password for the user credentials.

I am researching on this topic, about the user and password, and I have some questions:

  *   Can this user have MFA enabled?
  *   Where can I find the permissions assigned to this user?
  *   What permissions should this user have in a tenant and/or Azure subscription?
  *   Could this user be a service principal? Why is it not a service principal?

I will be waiting for your reply, have a good day!

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e3402c27-86a5-02f6-da5e-c49a614b2e67
  *   Version Independent ID: a574bc29-b33c-8eeb-ca04-983e6e08f7ea
  *   Content: Create an LCS connection in Azure Pipelines - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fdev-tools%2Fpipeline-lcs-connection%23feedback&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805807397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x8mXDTjxuS7UgLdP5JUTYWqUDcoyEP3DcMaHWGbgpdk%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/dev-tools/pipeline-lcs-connection.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fdev-tools%2Fpipeline-lcs-connection.md&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805807397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fjAjXT7632nm6L0rkOwOwoWVKLUUJmDTCNR2Xa9MrkM%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   GitHub Login: @jorisdg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjorisdg&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805817391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X6coSfpQEg4T77A0%2BEA5f5V95YtLLcRi0qJFjZrH%2Fx0%3D&reserved=0>
  *   Microsoft Alias: jorisde

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3574&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805827389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IPzK8H2duJruuZ90CRcEuo3do2GzFNX6QuqMHuIkmuY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD2EG2EWAQOB3NLPWCNCJB3UC43KTANCNFSM5EL75HNA&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805827389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3as4seLp65nplsEmIA6vkt2abkRZv4ygVMPz0r9ayAs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805837380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YX3bTIZmrWVbWjE%2BRwYKF7Z1zpT2vv9g%2FAUBoMs77Fc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjorisde%40microsoft.com%7Ca4c2bef7d52148e360c408d97c3d0592%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637677423805837380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3I9QwiT4yDVCjGoOgnLdoYwnsOwONzOwTteHNXz4MUY%3D&reserved=0>.

**Comment by RobinARH** [comment]
Created bug 623421 to track this issue.

**Comment by Beelzenef** [comment]
hello there!

I see that this issue was first marked as not-an-issue, but then a bug was created to track the progress.... is there any progress on this topic? We had no news since September 🔍

**Comment by davidop** [comment]
I am also very interested in knowing about the progress of this topic.

**Comment by davidop** [comment]
I am also very interested in knowing about the progress of this topic. Any news on bug 623421?
