### ISSUE TITLE
URL links for the Warehouse app are not updated and takes users to deprecated warehouse app. 

### ISSUE THREAD

**Issue by vpednekarqq** [MicrosoftDocs/dynamics-365-unified-operations-public#3614]
The current page links for downloading the Warehouse app is linked to deprecated App.
Please update the url to the new warehousing app. The other page is correctly linked https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app#install-the-app-from-an-app-store
 
Windows: https://www.microsoft.com/en-gb/p/warehouse-management/9pd35cdqcmg3?activetab=pivot:overviewtab
Andriod: https://play.google.com/store/apps/details?id=com.Microsoft.WarehouseManagement&hl=en_GB&gl=US

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2ac844-c345-707a-b2e9-5d4edf7c8541
* Version Independent ID: ae6e65c3-c1e1-c4cc-e05c-1c2ebd4bafc6
* Content: [Install and connect the Warehouse Management mobile app - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app)
* Content Source: [articles/supply-chain/warehousing/install-configure-warehouse-management-app.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/install-configure-warehouse-management-app.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @MarkusFogelberg
* Microsoft Alias: **mafoge**

**Comment by kamaybac** [comment]
@vpednekarqq , thank you for reporting this issue.

I looked into it, but I think the links are correct. We have two topics about setting up the mobile app:
- One topic is about the previous (depreciated) version ("warehouse app"), which is for customers that can't update to the new version yet (typically due to lagging mobile hardware). 
- The other topic covers the new version ("Warehouse Management mobile app"). 

Each topic has a colored box at the top that explains which version that topic describes. However, I might be confused, so please let me know if I am wrong. Here are the links I see:

**Warehouse Management mobile app (current version):**
- Install and setup topic: https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehouse-management-app
- Windows install link: https://www.microsoft.com/store/apps/9pd35cdqcmg3
- Android install link: https://play.google.com/store/apps/details?id=com.Microsoft.WarehouseManagement
 
**Warehouse app (deprecated version):**
- Install and setup topic: https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/install-configure-warehousing-app
- Windows install link: https://www.microsoft.com/store/apps/9p1bffd5tstm
- Android install link: https://play.google.com/store/apps/details?id=com.Microsoft.Dynamics365forOperationsWarehousing


Thanks,
. Karl
