### ISSUE TITLE
Service Bus Adapter > Custom Properties > Extending internal class according documentation raises an error

### ISSUE THREAD

**Issue by sfikh** [MicrosoftDocs/dynamics-365-unified-operations-public#3686]
Hi,

we send Business Events to Azure Service Bus and want to add a custom filter property for source system. We have implemented as described on this docs article in section "Extending filters so that they have custom fields (if the middleware supports this extension)". https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc#extending-filters-so-that-they-have-custom-fields-if-the-middleware-supports-this-extension

It worked with previous version, but now in D365 we get compile error with 10.0.23. PU47:

_'BusinessEventsServiceBusAdapter' is internal in model 'ApplicationFoundation' and cannot be extended by class 'BusinessEventsServiceBusAdapter_ABC_Extension' in model 'ABC'._

There was already the same issue #2990 created a year ago, but it was closed without any actions - neither documentation is updated, nor extension is allowed.

Please add a sample how to implement the additional property in a safe way since current suggestion cannot be compiled with actual version.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11811157-3f2d-56d5-07d4-0f44ab2c9370
* Version Independent ID: 5bc47a47-4d27-aaf5-750f-72b47bb39fe1
* Content: [Business events developer documentation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc)
* Content Source: [articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@***@***.***> and @***@***.***> can you pls help here?

Thanks
________________________________
From: sfikh ***@***.***>
Sent: Wednesday, November 24, 2021 6:43:19 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Service Bus Adapter > Custom Properties > Extending internal class according documentation raises an error (Issue #3686)


Hi,

we send Business Events to Azure Service Bus and want to add a custom filter property for source system. We have implemented as described on this docs article in section "Extending filters so that they have custom fields (if the middleware supports this extension)". https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/business-events/business-events-dev-doc#extending-filters-so-that-they-have-custom-fields-if-the-middleware-supports-this-extension<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fbusiness-events-dev-doc%23extending-filters-so-that-they-have-custom-fields-if-the-middleware-supports-this-extension&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029853510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T2LcJoCPilVdDZc9zsqqq1QlYHnKWStX5WUcCwsyjec%3D&reserved=0>

It worked with previous version, but now in D365 we get compile error with 10.0.23. PU47:

'BusinessEventsServiceBusAdapter' is internal in model 'ApplicationFoundation' and cannot be extended by class 'BusinessEventsServiceBusAdapter_ABC_Extension' in model 'ABC'.

There was already the same issue #2990<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F2990&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029863464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hx4%2B6bhh0pf73MRHxJOC3ECMMnDPeGnGRGh1AHzoSo8%3D&reserved=0> created a year ago, but it was closed without any actions - neither documentation is updated, nor extension is allowed.

Please add a sample how to implement the additional property in a safe way since current suggestion cannot be compiled with actual version.

Thanks.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 11811157-3f2d-56d5-07d4-0f44ab2c9370
  *   Version Independent ID: 5bc47a47-4d27-aaf5-750f-72b47bb39fe1
  *   Content: Business events developer documentation - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fbusiness-events-dev-doc&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029863464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f5p0YvMpQKk3PlbOdIatLVHgOjEEZXPplVRsGAHeXpU%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/business-events/business-events-dev-doc.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fbusiness-events%2Fbusiness-events-dev-doc.md&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029863464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xp3QnxKcZagmWsT7Pd4ZRh%2BGtg1ONzV9T4kbuBDGa0o%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029873421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X5Kkjk8PGllZEp%2B9l1%2BVdU6g0ui2rVg%2B1Mjr2t2x3U8%3D&reserved=0>
  *   Microsoft Alias: sunilg

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-unified-operations-public%2Fissues%2F3686&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029873421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LAYaqnVatfQn8KlWPBQIC%2B8ron%2BJXwMlEY2PH%2FUjXSE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHNKDW2N4ZZ6325WXB6YYX3UNT2YPANCNFSM5IWH2W2Q&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029883378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8uAPXZYR%2Br7rE1uPsbXP9SliAG4MDdrnMk9pzahTYuw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029883378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9BULeWotmtLrbJZVMUlCFUQDzz8y84H5WvfCQjSQMIs%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csunilg%40microsoft.com%7C5eb5b29be8334923880c08d9af58c271%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733618029893332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6M5zZcweftpgqOHNFRYyUHNy%2BlA7s0FsWcxY5fqfV4Y%3D&reserved=0>.

**Comment by Sunil-Garg** [comment]
It looks like we need to make that type public if we want extensions to be made on it.

I've reactivated the bug that was logged for the issue one year ago and assigned to myself to investigate.

https://msdyneng.visualstudio.com/FinOps/_workitems/edit/534663

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sfikh** [comment]
This would be the perfect solution, thanks!

**Comment by Sunil-Garg** [comment]
***@***.*** ***@***.***>

@***@***.***> can you pls update the PM ownership for this to @***@***.***>?

Thanks.

**Comment by sericks007** [comment]
I've assigned this issue, and the topic itself, to @jaredha.

**Comment by josaw1** [comment]
BUG 641736 created to track this issue.

**Comment by jaredha** [comment]
This issue has been fixed in PU49. The classes are public and available to extend, and the related documentation is updated.

**Comment by MatsWeigand** [comment]
Is there any plan to provide a backport of this to 10.0.23 / 24? We want to move to 10.0.24 but are currently blocked by this bug.
