### ISSUE TITLE
Year End Close page seems to have dated information.

### ISSUE THREAD

**Issue by jmholman331** [MicrosoftDocs/dynamics-365-unified-operations-public#3752]
We are unable to follow the documentation provided on the year end close.  We are unable to locate the screen that look like the screenshot regarding reverse the year-end close process or follow the process as outlined.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67434ec3-fdb0-02d2-e5c9-a80a0a646ac9
* Version Independent ID: 4765d614-15d7-f94f-0372-a901fbdf94b3
* Content: [Year-end close - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/general-ledger/year-end-close)
* Content Source: [articles/finance/general-ledger/year-end-close.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/year-end-close.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kweekley
* Microsoft Alias: **kweekley**

**Comment by kweekley** [comment]
This page contains the latest functionality around the GL year end close.  Please go to Feature management and enable the feature "General ledger year-end enhancements".  This feature splits the setup of the YEC template from the YEC processing.  The new processing form adds the audit trail of when the YEC was run, along with the option to reverse.  Please note that if you already ran the YEC, this new form will NOT show that previous YEC because the feature wasn't enabled yet.  To reverse the YEC using the old functionality, use the 'Undo' option on the YEC dialog.

**Comment by tonyafehr** [comment]
@jmholman331, thanks for the feedback. @kweekley, please review and address this.

**Comment by jmholman331** [comment]
Thanks for the reply.  We are looking at testing and turning on this feature.  This was very helpful.
