### ISSUE TITLE
Wrong or bad link in the article

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics-365-unified-operations-public#3768]
The link to https://aka.ms/dynamics_365_international_availability_deck ends up in nothing happens.
Here is the text.
Finance and Operations apps include functionality for the country/regions documented in the **_Product localization and translation availability guide_**. This functionality is enabled based on the primary address of the active legal entity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7482be7-1e0f-046a-bc69-27ad28fc4792
* Version Independent ID: e8b2e941-8906-7d70-b5db-f3f2ed2d71db
* Content: [Globalization resources - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/country-region?toc=%2Ffin-and-ops%2Ftoc.json)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/country-region.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lcs-solutions/country-region.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by kamaybac** [comment]
@amadse , thank you for getting in touch with us. I believe you also contacted me by email regarding this issue. I tested the link. It downloads a PDF instead of opening a web page, so please check your download folder. I'm closing this issue here for now, but please respond to my email if you are still having trouble with this link. Thanks.
