### ISSUE TITLE
No instruction available for Commerce SDK

### ISSUE THREAD

**Issue by fivefq** [MicrosoftDocs/dynamics-365-unified-operations-public#3940]
The article is outdated. The document has only reference to how use it if you are using Retail SDK. Retail SDK is being phased out and we are already on Commerce SDK. Please add instructions on how to this if you are using Commerce SDK. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38dea829-cc3f-2e72-8d57-5bc6d594b8b6
* Version Independent ID: ee57daf0-88ae-e3fe-a469-8508e231490e
* Content: [Deployment guidelines for cash registers for India - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/localizations/apac-ind-loc-deployment-guidelines?tabs=retail-10-0-6)
* Content Source: [articles/commerce/localizations/apac-ind-loc-deployment-guidelines.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/localizations/apac-ind-loc-deployment-guidelines.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @AlexChern0v
* Microsoft Alias: **jiaqia**

**Comment by josaw1** [comment]
Thank you for your feedback. @AlexChern0v can you please review?

**Comment by EvgenyPopovMBS** [comment]
Because of limitations of the new independent packaging and extension model and the Commerce SDK, it can't currently be used for the GST integration for India. You must use the previous version of the Retail SDK on a developer virtual machine (VM) in Microsoft Dynamics Lifecycle Services (LCS). Support for the new independent packaging and extension model for Commerce localizations is planned for later versions.
