### ISSUE TITLE
The Class 'ERImportFormatDataSourceContract'  is internal and is not accessible from the current module

### ISSUE THREAD

**Issue by deman** [MicrosoftDocs/dynamics-365-unified-operations-public#3977]
Hi,

In the sample code inside this page, it is using ERImportFormatDataSourceContract.

For the same usage in our code, we are getting this error:

C:\DynamicsSDK\Metadata\Microsoft.Dynamics.AX.Application.Build.targets(40,5): Error : Error: dynamics://Class/AxMT940BankStatementImport/Method/gerImportStatement(718,61) - The Class 'ERImportFormatDataSourceContract'  is internal and is not accessible from the current module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4daea5ec-1ec2-bb7d-317c-eae49e117127
* Version Independent ID: 42d924b9-d905-24ae-a45e-5e27f30ee031
* Content: [Initiate data source values of the USER INPUT PARAMETER type from source code - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-initiate-uip-data-source-value-from-source-code#feedback)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-initiate-uip-data-source-value-from-source-code.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-initiate-uip-data-source-value-from-source-code.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @NickSelin
* Microsoft Alias: **nselin**

**Comment by NickSelin** [comment]
Hello [deman](https://github.com/deman),
This code sample was published before the following [enhancement](https://fix.lcs.dynamics.com/Issue/Details/?bugId=648578&dbType=3) has been announced for the Dynamics 365 Development tooling. To adapt this code to the currently using tooling, refer the  **ERIImportFormatDataSourceContract** public interface instead of the **ERImportFormatDataSourceContract** internal class like the current version of the referred **BankStatementImportBatch** class does. We will update the sample code of this article accordingly.
Best regards,
Nick
