### ISSUE TITLE
Restart copy after DIXF batch failure

### ISSUE THREAD

**Issue by ThomasZak1** [MicrosoftDocs/dynamics-365-unified-operations-public#4005]
If the copy process fails, are there an special instructions for redoing or completing the copy? Is there any problem with just redoing the copy entirely after a partially complete copy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ca3366-fa7f-6cda-dfc6-672f032ccc3a
* Version Independent ID: 0bb7d0c2-467e-8a95-b7f1-51dbfe0b6b20
* Content: [Copy configuration data between companies or legal entities overview - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/copy-configuration)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/copy-configuration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/copy-configuration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @rcarlson
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@ThomasZak1, thanks for providing this feedback.  I asked a PM who responded with this: "Each entity will have a listing of success/failure and the user can address those issues and re-run just like they would with any other data project." 

The PM the referred to the following content in the article:

“Any errors that occur are shown on the Execution summary page, just as they are for an import project. You can edit the errors in the staging tables and resubmit the values for each data project.

**Special considerations when you copy into a legal entity**

When you copy into a legal entity, you have the same validation that occurs when you import a file. It's important that you test your copy in a test environment, so that you can identify any dependencies that will cause failures. If dependent information isn't included in your list of entities to copy, the entity will show errors when it tries to copy into the legal entity. For example, if a customer has a default site or warehouse, you must use one of these approaches:

•	Import the sites and warehouses as part of the copy.
•	Manually load the sites and warehouses before you copy the legal entity.
•	Unmap the site and warehouse fields before you copy the information.

You might also experience import errors if you copy from one region to another region. For example, you can have 1099 fields in a legal entity in the US region. However, if you try to import those values into a legal entity in a German region, you will see errors on the import. If a template that you load has entities that are incorrect for a region, you will receive an error message that states that the incorrect entity wasn't loaded. However, the rest of the template will continue to be loaded. You should copy only information that is appropriate for the destination region.”
