### ISSUE TITLE
Can't find the feature under feature management that is mentioned in the docs site

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/dynamics-365-unified-operations-public#4033]
[I can't find the below feature under feature management:

To view summary data from the general journal account entry, **enable the Amount details from the General journal account entry are displayed on the Trial balance with transactional detail report feature**.

I have the following platform version installed:

Installed product version : 10.0.25 (10.0.1149.131)
Installed platform version : Update49 (7.0.6316.102)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73deae8d-c248-76f5-8772-ae716556357f
* Version Independent ID: 2b2fe1f0-b294-20e2-78ab-f7c3533cb334
* Content: [Trial balance with transactional detail report - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/public-sector/general-ledger-public-sector-trial-balance)
* Content Source: [articles/finance/public-sector/general-ledger-public-sector-trial-balance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/public-sector/general-ledger-public-sector-trial-balance.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @v-kiarnd
* Microsoft Alias: **v-kiarnd**

**Comment by kamaybac** [comment]
@sbaber82 , all three of the mentioned features appear in 10.0.28 (see below). The feature you are asking about looks to have been added in March 2022, so that probably means you need version 10.0.26 or later to see it. 

![image](https://user-images.githubusercontent.com/26439921/171600570-b4e4a423-5da8-4263-bf55-5ee8a17d2d1b.png)

Thank you for contacting us regarding this help topic. I have forwarded your comment to the topic author for further consideration.

**Comment by sbaber82** [comment]
Thanks for the confirmation.I think it would be good to mention, under which build the feature has become available, just to avoid any confusion.

**Comment by kamaybac** [comment]
Thanks @sbaber82 . We don't usually mention version requirements for features in feature management because each version goes to auto-update 2-3 months after release, so this info goes quickly out of date. However, you are right that it is important info during that period. I will discuss our policy with the publishing group, but I will close this issue for now.
