### ISSUE TITLE
Could not find the CDS virtual entity application role

### ISSUE THREAD

**Issue by v3ux** [MicrosoftDocs/dynamics-365-unified-operations-public#4062]
Hi,

We have followed this step up correctly up till the step to assign **CDS virtual entity role** to the new user, but we couldn't find it.

However, we found these roles

![image](https://user-images.githubusercontent.com/108313663/176416866-590b0030-ec4c-49eb-b87a-e2c6eec9835b.png)

Are those the correct replacement for CDS virtual entity role? Since CDS is an old term used before new term (Dataverse) is introduced.

However if we use that, we could not get the result in advanced find in the next step. It ended up as an error.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities#generate-virtual-entities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
* Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
* Content: [Configure Dataverse virtual entities - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/admin-reference#grant-app-permissions-in-finance-and-operations-apps)
* Content Source: [articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by Sunil-Garg** [comment]
@Jared ***@***.***>
________________________________
From: v3ux ***@***.***>
Sent: Wednesday, June 29, 2022 3:38:26 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Could not find the CDS virtual entity application role (Issue #4062)


Hi,

We have followed this step up correctly up till the step to assign CDS virtual entity role to the new user, but we couldn't find it.

However, we found these roles

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F108313663%2F176416866-590b0030-ec4c-49eb-b87a-e2c6eec9835b.png&data=05%7C01%7Csunilg%40microsoft.com%7C1f291ce9436240bf00e608da59bb807b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637920959107688100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9eFfh1B%2FTPZvbs5gGlQVuJCKk2RFudQkAF6w9Smphw0%3D&reserved=0>

Are those the correct replacement for CDS virtual entity role? Since CDS is an old term used before new term (Dataverse) is introduced.

However if we use that, we could not get the result in advanced find in the next step. It ended up as an error.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/power-platform/enable-virtual-entities#generate-virtual-entities<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Fenable-virtual-entities%23generate-virtual-entities&data=05%7C01%7Csunilg%40microsoft.com%7C1f291ce9436240bf00e608da59bb807b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637920959107688100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zv2xNfgM5Fz%2FW8Kb%2Bs12iGwNtMYYYMOmzeQc6uFMMdQ%3D&reserved=0>

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 8065cd89-f253-c50b-ed2e-7b84e5b2409c
  *   Version Independent ID: 8c7e311a-582c-1ac6-328e-be817a62924c
  *   Content: Configure Dataverse virtual entities - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Fadmin-reference%23grant-app-permissions-in-finance-and-operations-apps&data=05%7C01%7Csunilg%40microsoft.com%7C1f291ce9436240bf00e608da59bb807b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637920959107688100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UbX%2F%2Bkh0HEDu14pzvo783xtPg2LvbFma9kNucnP%2Ffrs%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/dev-itpro/power-platform/admin-reference.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Fdev-itpro%2Fpower-platform%2Fadmin-reference.md&data=05%7C01%7Csunilg%40microsoft.com%7C1f291ce9436240bf00e608da59bb807b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637920959107688100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BoXarashuySKIr6P5UWLK7fggb9Nw%2B6fUF%2FgwQkCsm0%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=05%7C01%7Csunilg%40microsoft.com%7C1f291ce9436240bf00e608da59bb807b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637920959107688100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xz5%2B%2BpmbU%2BtS5VLm74n0uQTxidcFbrvNNCJVk%2Bq5e1I%3D&reserved=0>
  *   Microsoft Alias: sunilg

**Comment by jaredha** [comment]
Yes, this should have been changed. The names of the security roles were updated when the product name changed from "Common Data Service" to "Dataverse". The role to use for this scenario is "Dataverse Virtual entity integration app". I've submitted a PR to update the documentation.

**Comment by kfend** [comment]
@jaredha - Thank you for taking care of this so quickly. I have merged your PR and the article changes will show in the next few hours. I will close this issue.
