### ISSUE TITLE
Test evidence 

### ISSUE THREAD

**Issue by kesun1** [MicrosoftDocs/dynamics-365-unified-operations-public#4083]
[Enter feedback here]
Hi,

There is nothing discussed that FastTrack would refer to test result. It would be better partners provide test result such as Batch Import, export, etc to FTC for their review.

Thanks.
Keisuke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b23a0dbf-7870-affb-b07b-53b8ea704371
* Version Independent ID: 02442fdc-5733-1ab3-da37-a1e6dfc89c41
* Content: [Prepare for go-live - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live?toc=%2Fdynamics365%2Fcommerce%2Ftoc.json)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/prepare-go-live.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @ClaudiaBetz-Haubold
* Microsoft Alias: **chaubold**

**Comment by ClaudiaBetz-Haubold** [comment]
Dear Keisuke,

the FastTrack team does not provide a general service to review the project team’s test results as part of the Go-live Readiness Review. It is the project team’s responsibility to review the results and take appropriate action. For those projects that have a FastTrack engagement, the assigned Solution Architect might assist in that activity, if they deem it necessary to do so.

Kind regards,


***@***.***

Claudia Betz-Haubold | Principal Solution Architect | office:  +49.89.3176.2804
Dynamics 365 FastTrack

Please note: I am working part-time. Usual working days are Tuesday, Wednesday, Thursday.
Preferred meeting times: between 9 am and 6 pm CET (UTC +1).

***@***.***
Download the Implementation Guide Here!<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FD365ImplementationGuide&data=04%7C01%7CClaudia.Betz-Haubold%40microsoft.com%7C8bc2553bbc794bfedf4508d91a04c2ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637569430062120864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DtCtUiw%2FTCgZr%2BzVwhobq0jkLDBVh2Yj3eRuwsuh%2FdM%3D&reserved=0>
We work flexibly at Microsoft. If you receive an email from me outside of your normal business hours, I’m sending it at that time because it suits me. I’m not expecting you to read or reply until YOUR normal business hours. Thank you for your understanding.
