### ISSUE TITLE
Adding the PU

### ISSUE THREAD

**Issue by AliAAdamu** [MicrosoftDocs/dynamics-365-unified-operations-public#4153]
Hello, we should add the PU number with the application version as they get released at the same time and the support team mostly refer to the PU number rather than the application version when talks with the customers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dcb285-f32c-c92e-fe49-1617f213066b
* Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
* Content: [Service update availability - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/public-preview-releases)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @hmahl
* Microsoft Alias: **hmahl**

**Comment by hmahl** [comment]
Since we no longer release the platform version as a standalone package, the platform version number is a purely internal numbering system used by engineering. It’s the 10.0.xx application version that is used to identify combined app+plat package versions, so it is the application version number that should be used in discussions with customers.


From: AliAAdamu ***@***.***>
Sent: Tuesday, September 6, 2022 9:42 AM
To: MicrosoftDocs/dynamics-365-unified-operations-public ***@***.***>
Cc: Heather Mahl ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-unified-operations-public] Adding the PU (Issue #4153)


Hello, we should add the PU number with the application version as they get released at the same time and the support team mostly refer to the PU number rather than the application version when talks with the customers.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e7dcb285-f32c-c92e-fe49-1617f213066b
  *   Version Independent ID: 8f28c1a0-9da5-f853-90ee-d82a4c32df7e
  *   Content: Service update availability - Finance & Operations | Dynamics 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Ffin-ops-core%2Ffin-ops%2Fget-started%2Fpublic-preview-releases&data=05%7C01%7Chmahl%40microsoft.com%7C48ebfb4bf3124f70a66608da9026b039%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980793092380188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bdVjh4OMEHfdfCwJtw%2FBX6RTISfXWDb0wMJmpdGHj9I%3D&reserved=0>
  *   Content Source: articles/fin-ops-core/fin-ops/get-started/public-preview-releases.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FDynamics-365-Unified-Operations-Public%2Fblob%2Fmain%2Farticles%2Ffin-ops-core%2Ffin-ops%2Fget-started%2Fpublic-preview-releases.md&data=05%7C01%7Chmahl%40microsoft.com%7C48ebfb4bf3124f70a66608da9026b039%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980793092380188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nVlJnQM1hfoqXfq1on%2Fuz5qVNnggd6%2F49IXFjbRqoqg%3D&reserved=0>
  *   Service: dynamics-365-cross-app
  *   Product: ****
  *   Technology: ****
  *   GitHub Login: @hmahl<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmahl&data=05%7C01%7Chmahl%40microsoft.com%7C48ebfb4bf3124f70a66608da9026b039%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980793092380188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4Z4GsbW24vXJmjTNMxHjckF2VNdvk1F%2FSYb63axRwp4%3D&reserved=0>
  *   Microsoft Alias: hmahl
