### ISSUE TITLE
Can we update the price when the store is disconnected?

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4211]
Is it possible to update the price when the store is disconnected by using Commerce scale unit?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3904172-4dc3-3602-05a6-6bc0fcd1c7e3
* Version Independent ID: 2eaac493-f165-5f34-8d05-e441e741a8b8
* Content: [Commerce Scale Unit (self-hosted) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-store-system-begin)
* Content Source: [articles/commerce/dev-itpro/retail-store-system-begin.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/retail-store-system-begin.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 756034 has been logged to address this issue.

**Comment by josaw1** [comment]
@jashanno can you please review this?

**Comment by boycez** [comment]
It's not quite clear to me what the customer refers to by saying "update the price". If it's about price configuration in back-office system, sure you can do it regardless of POS connectivity status, because HQ and POS are technically two different systems. If it's about "price override" function in POS app, yes that's also supported for POS in offline mode, which is outlined in https://learn.microsoft.com/en-us/dynamics365/commerce/pos-operations @josaw1 Bug 756034 FYI
