### ISSUE TITLE
Code returns warnings

### ISSUE THREAD

**Issue by MichalBesta** [MicrosoftDocs/dynamics-365-unified-operations-public#4228]
[Enter feedback here]
Event handler code example returns following warnings: _IntrinsicArgIsNotAccessible: The argument 'ERFormatDestinationSettings' used in the intrinsic function 'formMethodStr' is not accessible. This warning will be turned into an error and must be addressed._

It is probably due to class ERFormatDestinationSettings that is internal and has same name as form. If event handler is moved to code extension then similar problems appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b02868d-cb47-076a-dd65-6093b79ede30
* Version Independent ID: be3e95fb-386d-b3bc-16d1-5bf1a6947a6d
* Content: [Implement a custom destination for generated documents - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/er-custom-file-destination?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/er-custom-file-destination.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/er-custom-file-destination.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by bishalgoswami** [comment]
Bug 758906 has been logged to address this issue.

**Comment by NickSelin** [comment]
Hello [MichalBesta](https://github.com/MichalBesta) 
Thank you for reporting this issue that has been registered as the defect 758906. Please, note that some changes were introduced in the platform this year to warn users not to call internal forms from outside of the model in which it has been implemented like it has been done earlier for tables. Most likely, you used the app build that contains a code defect due to which you have got that warning as the referred form is public. We did not manage to reproduce this case and get such a warning on the latest build of the 10.0.32 version. Therefore, you can use the provided code sample. Please, inform us if you manage to reproduce this case in further builds.
Regards,
Nick Selin
