### ISSUE TITLE
Would appreciate information on what happens when a number sequence reaches it's last number  e.g. SO-99999

### ISSUE THREAD

**Issue by butterflychaser** [MicrosoftDocs/dynamics-365-unified-operations-public#4345]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07ba5ded-583c-abed-87af-f5687fd2597d
* Version Independent ID: c35f7c6e-07a7-4c92-deaa-85a47e86b42e
* Content: [Number sequences overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/number-sequence-overview)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/number-sequence-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/number-sequence-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sunilgarg
* Microsoft Alias: **sunilg**

**Comment by bishalgoswami** [comment]
Bug 776280 has been logged to address this issue.

**Comment by johnmichalak** [comment]
1/9/23 Followed up with PM again today to check on status of potential changes.

**Comment by johnmichalak** [comment]
@butterflychaser I am so sorry it has taken me so long to get back to you. It took a while to track down an answer from the developers. When the number sequence has been exceeded, and error will display in the action center. The error is similar to this: Number sequence %1 has been exceeded. 

Do Note, you might notice inconsistent behavior with respect to Get Number call when the Number Sequence breaches the Highest value. i.e., One interaction might be able to fetch the next Number from number sequence and in others it might fails. 

This happens due to two reasons.

1. Caching of number by AOS process (interactive & Batch AOS) for non-continuous number sequence.
    
Reason :
              When caching is enabled, individual process will cache a set of numbers, when Get Number call land on machine which have cached some value, will be able to respond to Get Number call, where as other nodes that who have exhaust thier cached number would report error.
              
              
2. Recycling of number at a later point in time for continuous number sequence.

   Reason :           
              It is possible that few number got recycled when number Sequence clean-up ran, thereby Get Number call succeeding though few minutes back it would have reported "Number sequence %1 has been exceeded.".

I hope this helps.
