### ISSUE TITLE
Entity Store Name to be added

### ISSUE THREAD

**Issue by Harsh-Vaid** [MicrosoftDocs/dynamics-365-unified-operations-public#4637]
[Enter feedback here]

It will be of great help if the entity store names can be provided which need to be activated to ensure data is coming.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb95863-d804-395f-7146-3c352aa588ac
* Version Independent ID: 4bb08b32-dea2-090d-c27d-19408057f2d7
* Content: [Vendor payments workspace - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/accounts-payable/vendor-payments-workspace)
* Content Source: [articles/finance/accounts-payable/Vendor-payments-workspace.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/accounts-payable/Vendor-payments-workspace.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **shpandey**

**Comment by bishalgoswami** [comment]
Bug 834374 has been logged to address this issue.

**Comment by ankviklis** [comment]
Hello @Harsh-Vaid, according to the article, the ‘Vendor payment measure V2’ must be updated in order for the Analytics tab of the Vendor payments workspace to display data. However, the setup description needs to be revised because it is actually the ‘Vendor payment measure V3’ that needs to be refreshed. The ‘Setup needed to view Power BI content’ chapter will be updated consequently.

**Comment by ankviklis** [comment]
Hello @Harsh-Vaid, the article has been updated.
