### ISSUE TITLE
Samples validation

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#467]
Please, check samples - some of them look incorrect:
1)  &lt;/td&gt; - all samples are the same
2)  match("ab:dcd","ab123cd"); returns 0 - should not it return 1?
3)  match("ab: cd","ab cd"); returns 0 - should not it return 1?
 
"An expression that is followed by an asterisk" - asterisk is not displayed in any expression

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27a2af11-bc8e-9ffd-802c-12b3a91a739a
* Version Independent ID: dd23ab4f-2e5f-b99f-deae-28df175462ba
* Content: [X++ string runtime functions - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/dev-ref/xpp-string-run-time-functions)
* Content Source: [articles/dev-itpro/dev-ref/xpp-string-run-time-functions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/xpp-string-run-time-functions.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by pvillads** [comment]
The code is correct. The second one

match("ab:dcd","ab123cd"); returns 0

is correct since 123 is more than the one digit provided for. You may want to add this example to make that obvious:

match("ab:d*cd","ab123cd"); returns 1

(i.e. adding a * operator after the :d, which means "0 or more digits")

The example:
match("ab: cd","ab cd"); returns 0. Only the first space is matched

is also correct, but hinges on the fact that there should be TWO blanks after the : in the pattern.

I also noticed 
A right angle bracket (>) or a dollar sign **(?)** at …
