### ISSUE TITLE
Pattern count

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#472]
"If you don’t have a reason to use one of the other two patterns" - could you, please, clarify, which 2 patterns are meant? There are 4 patterns after 'Dialog' one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e5ddcc-3223-5080-7faa-7331daf71d00
* Version Independent ID: bd258d9d-caac-c4c6-a190-a48fefb7812c
* Content: [Dialog form pattern - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/dialog-form-pattern)
* Content Source: [articles/dev-itpro/user-interface/dialog-form-pattern.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/user-interface/dialog-form-pattern.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by jasongre** [comment]
Thanks for catching this. We added more patterns since this page was originally written, but did not update that line. It should just say "If you don't have a reason to use one of the other Dialog patterns."  The main idea is to use the simple plain Dialog pattern unless a more complex or read-only dialog is necessary.
