### ISSUE TITLE
This page is not useful at all

### ISSUE THREAD

**Issue by darione2178** [MicrosoftDocs/dynamics-365-unified-operations-public#4837]
Hi,

the part related to DOM exceptions and what they mean is missing completely. can you add it please?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b89b3109-e935-4ba8-db24-a7f553eec599
* Version Independent ID: e50c0b90-9348-3f1c-02da-362af63e683f
* Content: [Distributed order management (DOM) - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dom)
* Content Source: [articles/commerce/dom.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dom.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment]
Bug 878179 has been logged to address this issue.

**Comment by johnmichalak** [comment]
@darione2178 the overview topic was split into several related topics to make it easier to read. Is this the information you are looking for: https://learn.microsoft.com/en-us/dynamics365/commerce/dom-extensibility?

**Comment by darione2178** [comment]
Hi,

No, I need something far more basic: a list of DOM Processing statuses,
with an explanation of what they mean.

Thank you,

Dario

[image: image.png]

**Comment by darione2178** [comment]
![DOM_Processing_status](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/96228387/a51030b8-2d5c-4adf-b3d5-6311be59e03a)

**Comment by johnmichalak** [comment]
@darione2178 I have reached out to the author to see if this can be provided and added to the article. I will let you know as soon as I hear back.

**Comment by darione2178** [comment]
Hi John, thank you so much, it would be a very useful addition to this
topic.

**Comment by johnmichalak** [comment]
@darione2178 it turns out these are documented; however, the terminology is outdated. This is the correct terminology:

Not processed – The order line was never brokered.
Successful – The order line is successfully brokered and assigned to a location. 
Exception – The order line is brokered but can't be assigned to a location. 

I will work on fixing the terminology. Here is a link to the article: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdynamics365%2Fcommerce%2Fdom-runs-results%23%3A~%3Atext%3DThe%2520DOM%2520status%2520field%2520on%2Cbe%2520assigned%2520to%2520a%2520location.&data=05%7C02%7Cjohnmichalak%40microsoft.com%7Cc8fbb5faa6ad4fcf099008dc159cbb56%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638409010138589726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=10VaH3%2B%2BkTEMV1R45IwdWGQpDmQ8wIrHGbAQveSYzxY%3D&reserved=0
