### ISSUE TITLE
Data Events are not compatible with Cross-Company Data Sharing

### ISSUE THREAD

**Issue by abylkhatov** [MicrosoftDocs/dynamics-365-unified-operations-public#4861]
As per the feedback we received in the support ticket 2401090050001722 Data Events are not compatible with Cross-Company Data Sharing. This need to be added to the list of Limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07ba5d8f-e335-9d6f-0418-7529f19d558f
* Version Independent ID: 1ff0ba1d-54f0-8f59-49d3-c8ab44470cd9
* Content: [Cross-company data sharing - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by w-azure** [comment]
Hi @abylkhatov,

Thanks for reaching out.
There was a bug with cross-company data sharing which blocked tables from being shared when the business events were enabled on tables or vice versa. This bug is fixed now. The only restrictions with cross-company data sharing are with dual write, but it's documented already.
Thanks again.
