### ISSUE TITLE
Is this an independent copy or a linked copy

### ISSUE THREAD

**Issue by ThomasZak** [MicrosoftDocs/dynamics-365-unified-operations-public#598]
I have users reporting to me that after they copy a customer from Company A to company B, then if they update one of the fields on the customer in company A, then that same change occurs in company B. Is this intentional? Is it documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c3af4f-aa47-fb1b-4e89-cba689ed93c5
* Version Independent ID: cd2487c5-b203-34be-c5ed-06439b82e0f1
* Content: [Copy customers by using shared number sequences - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/accounts-receivable/copy-customer)
* Content Source: [articles/financials/accounts-receivable/copy-customer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/accounts-receivable/copy-customer.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mikefalkner
* Microsoft Alias: **mikefalkner**

**Comment by mikefalkner** [comment]
The feature is an independent copy. It is the same process that you would go through to find an existing party, create a customer, and then manually update all of the fields to match. However, the customers are linked by the party ID so, if you change something that is party-related (like the customer name), it will change in both place. Otherwise, it will not continually keep the copy of the customer updated.

**Comment by tonyafehr** [comment]
Thanks @mikefalkner, I'm closing this comment based on your reply.
