### ISSUE TITLE
Add financial dimensions lookup for OData

### ISSUE THREAD

**Issue by anderson-joyle** [MicrosoftDocs/dynamics-365-unified-operations-public#604]
This add-in can be useful: https://github.com/anderson-joyle/D365FO-ExcelFinancialDimensionLookups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde2d80e-b399-585f-8a79-24992d5a3748
* Version Independent ID: d8d50079-7de8-b443-67a5-9e7c2189d0b9
* Content: [Add lookup values for financial dimensions to Excel templates - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/add-dimensions-excel-templates)
* Content Source: [articles/dev-itpro/financial/add-dimensions-excel-templates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/add-dimensions-excel-templates.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by sericks007** [comment]
Bug 270370 has been logged to track this issue.

**Comment by Tjsonata054** [comment]
We have followed the link and added the lookup for dimensions , but the lookup is not showing more than 999 records . Can anyone know regarding this issue?

**Comment by anderson-joyle** [comment]
@Tjsonata054  Never hear about this. Is this happening for all dimensions? Default and custom value ones? One thing that I noticed while ago was that when you create a DimensionCombinationEntity/DimensionSetEntity extension element, if you change the sufix (*.Extension) to something else it behaves badly. Can you try to leave your extension element as *.Extension?

**Comment by aprilolson** [comment]
The lookup control in Excel is limited to 999 rows. After that you must use filtering capabilities.

**Comment by aprilolson** [comment]
I commented. Can we close it? How do I do that?

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by Tjsonata054** [comment]
Thanks for the reply @aprilolson . yes you can close it .

**Comment by RajendraShivaraya** [comment]
After following the document, I was able to add the financial dimensions as separate columns with lookups. I see lookups work great with standard dimensions. But for custom fin dimensions, I can see all custom fin dimension values in the lookup instead of just the selected one. ex : I have 4 custom dimension, Dim1, Dim2, Dim3, Dim4. When I select Dim3 in excel, all the dimension values of Dim1, Dim2, Dim3, & Dim4 are showing up in the lookup.

**Comment by piyush0374** [comment]
> After following the document, I was able to add the financial dimensions as separate columns with lookups. I see lookups work great with standard dimensions. But for custom fin dimensions, I can see all custom fin dimension values in the lookup instead of just the selected one. ex : I have 4 custom dimension, Dim1, Dim2, Dim3, Dim4. When I select Dim3 in excel, all the dimension values of Dim1, Dim2, Dim3, & Dim4 are showing up in the lookup.

Have You got any solution for this @RajendraShivaraya?
