### ISSUE TITLE
Data mart reset issue in one box environment (Installed platform version : Update15)

### ISSUE THREAD

**Issue by EkambaramPazhanisami** [MicrosoftDocs/dynamics-365-unified-operations-public#608]
When we do the data mart reset as described above from Report designer, the report designer crashes and the error log is recorded with the below error messages. The same result is displayed while doing from power-shell using "Reset-DatamartIntegration" command.
Machine: XXXXX
	{"Class":16,"Number":8169,"State":2,"Message":"Conversion failed when converting from a character string to uniqueidentifier.","ErrorCode":-2146232060,"Procedure":"","LineNumber":2,"Errors":[{"Class":16,"Number":8169,"State":2,"Message":"Conversion failed when converting from a character string to uniqueidentifier.","Procedure":"","LineNumber":2,"Source":".Net SqlClient Data Provider"}],"ConnectionId":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","Source":".Net SqlClient Data Provider"}.

Please let me know if I am missing something or data mart reset will not work in downloaded VM(one box environment)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcccc152-564f-c7cb-ccbd-06686e3ae999
* Version Independent ID: ecbaf175-9401-36f5-d416-95b26823bf11
* Content: [Reset the Financial reporting data mart - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore)
* Content Source: [articles/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/reset-financial-reporting-datamart-after-restore.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by josaw1** [comment]
Thanks for your comment. I've forwarded this on to the engineering team. Check back for their response.

**Comment by EkambaramPazhanisami** [comment]
Thank you so much, Josaw1. Please let me know if you have any updates.

**Comment by sericks007** [comment]
Bug 270380 has been logged to track this issue.

**Comment by aprilolson** [comment]
This is a support case, not a doc issue. Why would we track this on doc?

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by EkambaramPazhanisami** [comment]
Hello aprilolson, Thanks for your response. I just wanted to know that the procedure listed here is not working for one box environment (downloaded VM) also there is no details specific to one box environment in the given procedure. Since the given procedure is not working in one box environment, I just wanted to know is there any doc or steps available related to data mart reset in one box environment.

**Comment by aprilolson** [comment]
You are not missing anything from what I can tell. There seems to be an issue on that specific environment and a support ticket should be logged.

**Comment by aprilolson** [comment]
Ekahmbaram,
We would like to look at the issue. Did you raise this with support? If so, please let us know the ticket number so we can make sure look into it.

April Olson
Dynamics 365 Finance & Operations
Principal Group Program Manager, Financials & Service Industries

Our workplace allows for a flexibile work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until its convenient for you.

**Comment by ShylaThompson** [comment]
As steps have been verified, closing as a support request. @EkambaramPazhanisami please let @aprilolson know about your support ticket number and she can help following that route.

**Comment by TrudAX** [comment]
On the local One box you can use the following hint to perform a full DM reset
https://denistrunin.com/financial-reporting-local-onebox/
