### ISSUE TITLE
ExtendedDataSecurity

### ISSUE THREAD

**Issue by OksanaKovaliova** [MicrosoftDocs/dynamics-365-unified-operations-public#635]
Hi, 
Could you, please, provide a bit more detailed information about ExtendedDataSecurity? It is not clear on which part of application logic it influences. 
Thank you

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c7d5f5d5-c95d-4c70-0af6-69bb881052e6
* Version Independent ID: 2dbf3828-ed0d-06c9-0e07-1335951a9637
* Content: [Application Explorer properties - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/es-es/dynamics365/unified-operations/dev-itpro/dev-ref/application-explorer-aot-properties)
* Content Source: [articles/dev-itpro/dev-ref/application-explorer-aot-properties.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/dev-ref/application-explorer-aot-properties.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @RobinARH
* Microsoft Alias: **robinr**

**Comment by pvillads** [comment]
There really is not much more to add than what the description says: "Specify whether the menu item appears under all companies instead of in the context of a single company. The default value is No." That is the only impact on the system. There is no impact on any business logic in addition to this. The name is rather poor. It would have been better if it had read "CompanySpecific" or something along those lines.

**Comment by OksanaKovaliova** [comment]
Hi Peter,

Thank you for reply.

All menu items appear cross-company by default – you add it to menu and can see in any company.
If default value No means ‘item appears in a single company’ – then D365 does not work like this now… So this is my difficulty to understand why ‘No’ is ‘Yes’.

Regards,
Oksana
