### ISSUE TITLE
Data entities have neither modified time nor updated time field.

### ISSUE THREAD

**Issue by Tilerphy** [MicrosoftDocs/dynamics-365-unified-operations-public#646]
The records in DataEntity have neither modified time nor updated time field. It is impossible to query in the specific range time. Is there some solution to resolve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e2729b-116a-728c-1166-3c1a0cba9921
* Version Independent ID: 7c745e05-b5f4-40b6-65e1-395deeb17f1b
* Content: [Data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities)
* Content Source: [articles/dev-itpro/data-entities/data-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **sunilg**

**Comment by tonyafehr** [comment]
@Tilerphy, thanks for posting!
@Sunil-Garg, please answer this question and update the topic, as necessary.

In the meantime, to get product help you can contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 for Finance and Operations community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by rayzorben** [comment]
If it is not exposed by default, is it possible to query via ODATA only for changes when change tracking is enabled?

**Comment by tonyafehr** [comment]
Bug 274058 has been logged to track this issue.

**Comment by hellevik** [comment]
Because data entities can represent complex queries there is not an automatic map to a specific row in a specific table that can be used to represent a created date or modified date.  

Change tracking as it is implemented in the product is not date based, but uses SQL Server's change tracking tables.

Even if we did project created / modified from a source table onto the entity, querying on these fields would inefficient unless the underlying fields were indexed.

If created / modified fields is required for a specific entity we recommend adding them manually to the entity, and making sure they are included in an index to ensure an efficient query.  Then use SQL Server Management Studio to analyze the performance of the resulting view in the context of expected OData queries to verify performance.
