### ISSUE TITLE
Admin User Provisioning tool

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#660]
How do we use the Admin User Provisioning Tool in a VM that does not allow admin access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8987a0ce-dad0-3bf5-8681-500388d83645
* Version Independent ID: 0b8cee00-76d7-fad7-5dff-566aa325669a
* Content: [Development and build VMs that don't allow admin access FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/sysadmin/vms-no-admin-access)
* Content Source: [articles/dev-itpro/sysadmin/VMs-no-admin-access.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/sysadmin/VMs-no-admin-access.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @yukonpeegs
* Microsoft Alias: **epegors**

**Comment by yukonpeegs** [comment]
Using the admin user provisioning tool is not currently supported for development and build VMs that don't allow admin access. We will add this to the FAQ on this topic and you can watch the FAQ for updates. An add-on environment will be on the customer's tenant and you can change the email address of the environment's admin user as long as you have another admin user. We'd like to hear your scenario for changing the tenant of an add-on environment.

**Comment by dhand01** [comment]
This is not an add-on environment. This is a DEV/TEST or BUILD environment (Tier 1) that is part of a subscription. Now that admin access is not allowed on the server, there doesn't seem to be anyway to use the Admin User Provisioning Tool.

**Comment by yukonpeegs** [comment]
Do you want to change the domain of the admin user (from admin@company1.com to admin@company2.com) or just the email address (from admin1@company.com to admin2@company.com)?

**Comment by dhand01** [comment]
Scenario would be... Get latest copy of production data down in a DEV/TEST/BUILD box. Since a developer is not a user in the PROD DB, we normally add them as Admin to the DB using the Admin User Provisioning Tool. Now that this tool is inoperable, we have no way to add the dev user into the DB.

**Comment by yukonpeegs** [comment]
You can update the SID and network alias in the database to a known good value that is compatible with the target environment. The user can be added to any environment on the same tenant to get the correct SID. Note that the SID for a user for dev@company.com on an environment on the company.com tenant will be different than the SID for a user for dev@company.com on another tenant (e.g. partner.com because the dev environment is in the partner's LCS project). As long as the source environment is on the same tenant as the target environment, updating the SID and network alias in the database will work. If this doesn't work, the SID is likely not correct for the target environment.

-- get value from source env.
select ID, SID, NETWORKALIAS
from USERINFO
where ID = 'Admin'

-- update value in target env.
update USERINFO
set SID = 'new_SID',
	NETWORKALIAS = 'new_NetworkAlias'
where ID = 'Admin'

**Comment by dhand01** [comment]
Wow. So convenient! :)
Are there any plans to make the Admin User Provisioning Tool available again, for non-admins in DEV environments?

**Comment by yukonpeegs** [comment]
I will add an entry for the Admin User Provisioning Tool and the above information to this topic. You can check this topic for any future updates.

**Comment by ShylaThompson** [comment]
@dhand01 , I'm going to close this issue, as @yukonpeegs has responded and will update the topic.

**Comment by duonghoanghai** [comment]
^^!;
