### ISSUE TITLE
Just-time-access

### ISSUE THREAD

**Issue by Daxture** [MicrosoftDocs/dynamics-365-unified-operations-public#715]
"You will not have SQL Server access on Tier 2+. You will continue to have SQL database access using just-in-time access."

What does it mean by just-time-in access? And will that access be enough to troubleshoot issues like to look for even logs?

**Comment by ShylaThompson** [comment]
@Daxture thanks for commenting. The following topic might help: [Manage virtual machine access using just-in-time](https://docs.microsoft.com/en-us/azure/security-center/security-center-just-in-time). 

Can you tell me which topic you copied the following statement from? I'll assign this issue to the author.

"You will not have SQL Server access on Tier 2+. You will continue to have SQL database access using just-in-time access."

**Comment by sericks007** [comment]
This sentence is part of the [Self-service deployment](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/infrastructure-stack) topic.  

@sarvanisathish, can you please answer the question and update the topic, as needed.

**Comment by sarvanisathish** [comment]
@Daxture , instead of having persistent access to the SQL database, you will be able to request access via LCS to the database when you need to access the database, receive access and log into it. This is a standard security model that will protect your database at all times. @manalidongre for additional information.

**Comment by manalidongre** [comment]
@Daxture  - As Sarvani mentioned instead of persistent access (where credentials are static and are always shown) to the **Azure SQL database**, you will now request access through LCS to see the credentials only when you need them. The request is auto-approved so it is a matter of a minute or so where you see the database access credentials. These creds will be valid for 8 hours after which they expire. After 8 hours you will need to request access again. We are working on updating the FAQ with more information on the steps.  You will not have access to see the event viewer logs through RDP. For telemetry logs you can use LCS. For general event viewer logs, if you can share in what scenarios you use them, I can see what features we have that will enable you to achieve the same thing.
