### ISSUE TITLE
Purpose of the feature

### ISSUE THREAD

**Issue by vavd** [MicrosoftDocs/dynamics-365-unified-operations-public#750]
Could you provide business cases when this exact feature can be useful. Is this used for eliminating penny amounts for closing invoices? Any other examples? 
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b5ba84-203c-6b2a-32e5-e081197524d9
* Version Independent ID: e9a4760d-e0a0-4525-54e2-a7ff5dd9239e
* Content: [Settle remainder - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/financials/cash-bank-management/settle-remainder)
* Content Source: [articles/financials/cash-bank-management/settle-remainder.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/financials/cash-bank-management/settle-remainder.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @mikefalkner
* Microsoft Alias: **mikefalkner**

**Comment by sericks007** [comment]
@vavd, thanks for posting this!

@mikefalkner, please review and update the topic as suggested.

**Comment by mikefalkner** [comment]
@vavd   We already have a way to remove penny amounts. However, there are situations where you want to close out an invoice after a payment is made. It may have a deduction of some kind (rebate, return, overcharge) that you want to deal with immediately instead of creating a new item, posting it, and then coming back to settle it. It also provides you with a way to move remaining amounts to another customer or vendor.

**Comment by vavd** [comment]
@mikefalkner, many thanks for your reply.
