### ISSUE TITLE
Documentation about how to change the number of decimals is missing

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#792]
This Extensibility feature has been introduced with 8.1 IIRC. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab86cf5-9cb0-f51b-3ac8-7f16ccef799a
* Version Independent ID: 1bbfad2d-92a3-d3aa-058f-b6c179906c55
* Content: [Modify extended data types (EDTs) through extension - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/modify-edt)
* Content Source: [articles/dev-itpro/extensibility/modify-edt.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/extensibility/modify-edt.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ivanv-microsoft
* Microsoft Alias: **ivanv**

**Comment by ivanv-microsoft** [comment]
We have described that here:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/decimal-point-precision<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Funified-operations%2Fdev-itpro%2Fextensibility%2Fdecimal-point-precision&data=02%7C01%7Civanv%40microsoft.com%7C6b7db31d7c3e46270a2c08d67bc03291%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636832462747622198&sdata=7NturMWiNJ53mhddkkLbtqN6Xfvma0%2B924ktQaiXuJY%3D&reserved=0>



Ivan (Vanya) Kashperuk | Senior Engineering Manager | Microsoft Dynamics 365 for Finance and Operations | Microsoft Development Center Copenhagen | http://kashperuk.blogspot.com<http://kashperuk.blogspot.com/>

Our workplace allows for a flexible work schedule. I am sending this email now because it is convenient for me. I do not expect you to read or respond to this email until it is convenient for you.

**Comment by sericks007** [comment]
@torbennehmer, thanks for posting this.  Can you help me understand, are there any changes you'd like to see to the topic, or is there any information in the topic that is incorrect?

**Comment by sericks007** [comment]
Thanks @ivanv-microsoft!  

@torbennehmer, please see [Extending decimal point precision for selected data types](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/decimal-point-precision).

**Comment by torbennehmer** [comment]
@ivanv-microsoft : Thanks for the link, I simply missed that one. 

@sericks007 : May I suggest to hyperlink the two pages? On top of the "Extending EDTs" pages there is no mention of decimals. Maybe in the bullet list on the top something like "See <here> for information about extending decimal places for selected types" ?

If possible, please also clarify, if ISVs can make similar extensions possible and - if yes - how.

**Comment by sericks007** [comment]
@ivanv-microsoft or @kfend, could you please update the article as @torbennehmer suggested.  Thanks!
