### ISSUE TITLE
What is the release timing for each ring?

### ISSUE THREAD

**Issue by taylordgordon** [MicrosoftDocs/dynamics-365-unified-operations-public#811]
Given a release date like April 1st, which ring is being released that day?  Is it the GA ring?  Or would GA be released several weeks later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14372486-6284-da4b-6bbb-30acd36dd7de
* Version Independent ID: f8301c48-61db-e9e5-aba5-413528cd91d2
* Content: [One Version service updates FAQ - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/one-version)
* Content Source: [articles/fin-and-ops/get-started/one-version.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-and-ops/get-started/one-version.md)
* Service: **dynamics-ax-applications**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by tonyafehr** [comment]
@taylordgordon, I've assigned your question to @meeramahabala who can provide more details about this. Thanks!

**Comment by glenturnbullazure** [comment]
In the meantime, in case it helps @taylordgordon, I will try to answer based on my understanding of what is public knowledge. The following documents give an overview: https://docs.microsoft.com/en-us/dynamics365/get-started/release-schedule
https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases There are no hard dates for each ring, it depends on how testing of the current ring goes before progressing to the next ring, based on a quality bar. GA is due to be released on 5th April and other key official dates are here: https://dynamics.microsoft.com/en-gb/business-applications/release/#release-calendar. So First Release is going to be a some point between the PEAP date mentioned there and GA. I hope it helps!

**Comment by meeramahabala** [comment]
Please see https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/public-preview-releases for the schedule for the next few releases.
