### ISSUE TITLE
Upgrade first step

### ISSUE THREAD

**Issue by gprodware** [MicrosoftDocs/dynamics-365-unified-operations-public#830]
Hi,
Can we deploy a new Dev and Build ver 8.1.3 PU23 instead of deploying a 8.1 Up20 Environments and then Applying the latest binary update (8.1.3 PU23) ?
Thanks,
Gill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b5ec6-1a21-e71a-df38-ba497f7f1116
* Version Independent ID: d1e49823-7934-6a3a-50e1-547cdd632077
* Content: [Update environments from version 8.0 to 8.1.X - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/appupdate-80-81)
* Content Source: [articles/dev-itpro/migration-upgrade/appupdate-80-81.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/appupdate-80-81.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by ShylaThompson** [comment]
@laneswenka can you review this and update the topic if necessary.

**Comment by laneswenka** [comment]
Hi @gprodware yes you can deploy 8.1.3 PU23 but there are cases where this is the base version and we have since hotfixed either the app or the platform.  When you deploy the 8.1.X build server it is good to ensure your environment is up to the latest which is what the documentation is asking you to do.
