### ISSUE TITLE
k

### ISSUE THREAD

**Issue by YESChristianSchulte** [MicrosoftDocs/dynamics-365-unified-operations-public#911]
I have problems while importing into an existing Organization with System language German,
as all Numbers are #.## and in Germany they are #,##
is there a way to avoid those import problems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc92d46-8f1c-dc72-82c0-dcbccf014c18
* Version Independent ID: 934a9f55-fd2a-a08c-b8ce-cfd0c1fbb975
* Content: [Generate demo data by using data packages - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/generate-demo-data-packages)
* Content Source: [articles/dev-itpro/data-entities/generate-demo-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/generate-demo-data-packages.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @ryansandness
* Microsoft Alias: **ryansand**

**Comment by ryansandness** [comment]
I *think* this is controlled by System parameters. If in your blank system you check the general tab for system options, my default is en-us with a system currency of USD. Can you try changing these defaults before importing?

Otherwise it is a setting somewhere else that controls this formatting. The only other alternative would be to change the format of individual imports, but that would likely be a pain.

**Comment by YESChristianSchulte** [comment]
I had to change the settings of the Excel SOURCE DATA FORMATS to en-us.

**Comment by ryansandness** [comment]
Thank you for sharing the solution! Much appreciated.

**Comment by sericks007** [comment]
Bug 293657 has been logged to track this issue.

**Comment by ryansandness** [comment]
So previously you mentioned changing Excel SOURCE DATA FORMATS to en-us. If you are having issues with mismatch of separators, I assume you need to change the user settings for (Settings > User Options > Preferences) and set Date, time, and number format. Otherwise if you're still having issues it may be best to log a bug with step by step instructions that I can walk to make sure I understand the context. 

Thanks
